import type { NextRequest } from 'next/server'
import { assertSafeMutation, optionsResponse, parseJson, withAuthHeaders } from '@/modules/identity/interface/auth-http'
import { requireAuthenticatedUser } from '@/modules/identity/interface/request-authenticator'
import { getGuestService } from '@/modules/guests'; import { guestErrorResponse } from '@/modules/guests/interface/guest-http'; import { guestIdSchema, updateGuestSchema } from '@/modules/guests/interface/guest-schemas'; import { getRequestId, jsonResponse } from '@/shared/http/api-response'; import { weddingIdSchema } from '@/modules/weddings/interface/wedding-schemas'
export const dynamic = 'force-dynamic'; export const OPTIONS = optionsResponse; type Context = { params: Promise<{ weddingId: string; guestId: string }> }
async function ids(context: Context) { const params = await context.params; return { weddingId: weddingIdSchema.parse(params.weddingId), guestId: guestIdSchema.parse(params.guestId) } }
export async function GET(request: NextRequest, context: Context) { const requestId = getRequestId(request); try { const { actor } = await requireAuthenticatedUser(request); const p = await ids(context); return withAuthHeaders(jsonResponse({ guest: await getGuestService().get(actor, p.weddingId, p.guestId) }), requestId) } catch (error) { return guestErrorResponse(error, requestId) } }
export async function PATCH(request: NextRequest, context: Context) { const requestId = getRequestId(request); try { assertSafeMutation(request); const { actor } = await requireAuthenticatedUser(request); const p = await ids(context); return withAuthHeaders(jsonResponse({ guest: await getGuestService().update(actor, p.weddingId, p.guestId, await parseJson(request, updateGuestSchema)) }), requestId) } catch (error) { return guestErrorResponse(error, requestId) } }
export async function DELETE(request: NextRequest, context: Context) { const requestId = getRequestId(request); try { assertSafeMutation(request); const { actor } = await requireAuthenticatedUser(request); const p = await ids(context); await getGuestService().remove(actor, p.weddingId, p.guestId); return withAuthHeaders(new Response(null, { status: 204 }), requestId) } catch (error) { return guestErrorResponse(error, requestId) } }
