import { Prisma, type PrismaClient } from '@prisma/client'
import { createHash, randomBytes } from 'node:crypto'
import type { CreateCategoryData, CreateGuestData, CreateGroupData, CreateInvitationData, GuestRepository, UpdateGuestData, PublicInvitationView, UpdateCategoryData, GuestExportRow, GuestImportRow } from '../application/ports'
import { GuestError } from '../domain/guest-error'

const guestSelect = { id: true, weddingId: true, categoryId: true, groupId: true, displayName: true, phone: true, email: true, note: true, tableName: true, maxPartySize: true, tags: true, createdAt: true, updatedAt: true } satisfies Prisma.GuestSelect
const categorySelect = { id: true, weddingId: true, parentId: true, name: true, depth: true, sortOrder: true, createdAt: true, updatedAt: true } satisfies Prisma.GuestCategorySelect
const groupSelect = { id: true, weddingId: true, name: true, note: true, createdAt: true, updatedAt: true } satisfies Prisma.GuestGroupSelect
const invitationSelect = { id: true, weddingId: true, guestId: true, label: true, publicSlug: true, status: true, maxPartySize: true, expiresAt: true, revokedAt: true, lastViewedAt: true, createdAt: true, updatedAt: true } satisfies Prisma.InvitationSelect
const encode = (value: { createdAt: Date; id: string }) => Buffer.from(JSON.stringify([value.createdAt.toISOString(), value.id])).toString('base64url')
function decode(cursor?: string) { if (!cursor) return undefined; try { const [createdAt, id] = JSON.parse(Buffer.from(cursor, 'base64url').toString()) as [string, string]; return { createdAt: new Date(createdAt), id } } catch { return undefined } }
function token() { return randomBytes(32).toString('base64url') }
function tokenHash(value: string) { return createHash('sha256').update(value).digest('hex') }
function slugBase(value: string) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/đ/gi, 'd').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 140) || 'guest' }
export class PrismaGuestRepository implements GuestRepository {
  constructor(private readonly prisma: PrismaClient) {}
  private ownedWhere(userId: string, weddingId: string) { return { id: weddingId, createdById: userId, deletedAt: null } }
  private async owns(userId: string, weddingId: string) { return Boolean(await this.prisma.wedding.findFirst({ where: this.ownedWhere(userId, weddingId), select: { id: true } })) }
  private async validateReferences(weddingId: string, data: { categoryId?: string | undefined; groupId?: string | undefined }) {
    if (data.categoryId !== undefined && !await this.prisma.guestCategory.findFirst({ where: { id: data.categoryId, weddingId, deletedAt: null }, select: { id: true } })) throw new GuestError('GUEST_CATEGORY_NOT_FOUND', 404, 'Guest category not found')
    if (data.groupId !== undefined && !await this.prisma.guestGroup.findFirst({ where: { id: data.groupId, weddingId, deletedAt: null }, select: { id: true } })) throw new GuestError('GUEST_GROUP_NOT_FOUND', 404, 'Guest group not found')
  }
  async listOwned(userId: string, weddingId: string, filter: { query?: string | undefined; categoryId?: string | undefined; groupId?: string | undefined; limit: number; cursor?: string | undefined }) {
    if (!await this.owns(userId, weddingId)) return null
    const cursor = decode(filter.cursor)
    const rows = await this.prisma.guest.findMany({ where: { weddingId, deletedAt: null, ...(filter.categoryId ? { categoryId: filter.categoryId } : {}), ...(filter.groupId ? { groupId: filter.groupId } : {}), ...(filter.query ? { displayName: { contains: filter.query, mode: 'insensitive' } } : {}), ...(cursor ? { OR: [{ createdAt: { lt: cursor.createdAt } }, { createdAt: cursor.createdAt, id: { lt: cursor.id } }] } : {}) }, select: guestSelect, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], take: filter.limit + 1 })
    const hasNextPage = rows.length > filter.limit; const items = rows.slice(0, filter.limit)
    return { items, nextCursor: hasNextPage && items.length ? encode(items[items.length - 1]!) : null }
  }
  async findOwned(userId: string, weddingId: string, guestId: string) { if (!await this.owns(userId, weddingId)) return null; return this.prisma.guest.findFirst({ where: { id: guestId, weddingId, deletedAt: null }, select: guestSelect }) }
  async createOwned(userId: string, weddingId: string, data: CreateGuestData) { if (!await this.owns(userId, weddingId)) return null; await this.validateReferences(weddingId, data); try { return await this.prisma.guest.create({ data: { weddingId, displayName: data.displayName, maxPartySize: data.maxPartySize, tags: data.tags, ...(data.categoryId !== undefined ? { categoryId: data.categoryId } : {}), ...(data.groupId !== undefined ? { groupId: data.groupId } : {}), ...(data.phone !== undefined ? { phone: data.phone } : {}), ...(data.email !== undefined ? { email: data.email } : {}), ...(data.note !== undefined ? { note: data.note } : {}), ...(data.tableName !== undefined ? { tableName: data.tableName } : {}) }, select: guestSelect }) } catch (error) { if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === 'P2025') return null; throw error } }
  async updateOwned(userId: string, weddingId: string, guestId: string, data: UpdateGuestData) { if (!await this.owns(userId, weddingId)) return null; await this.validateReferences(weddingId, data); const cleanData = Object.fromEntries(Object.entries(data).filter(([, value]) => value !== undefined)); const result = await this.prisma.guest.updateMany({ where: { id: guestId, weddingId, deletedAt: null, wedding: this.ownedWhere(userId, weddingId) }, data: cleanData }); return result.count ? this.findOwned(userId, weddingId, guestId) : null }
  async deleteOwned(userId: string, weddingId: string, guestId: string) { if (!await this.owns(userId, weddingId)) return null; const result = await this.prisma.guest.updateMany({ where: { id: guestId, weddingId, deletedAt: null, wedding: this.ownedWhere(userId, weddingId) }, data: { deletedAt: new Date() } }); return result.count === 1 }
  async listCategories(userId: string, weddingId: string) { if (!await this.owns(userId, weddingId)) return null; return this.prisma.guestCategory.findMany({ where: { weddingId, deletedAt: null }, select: categorySelect, orderBy: [{ depth: 'asc' }, { sortOrder: 'asc' }, { name: 'asc' }] }) }
  async createCategory(userId: string, weddingId: string, data: CreateCategoryData) { if (!await this.owns(userId, weddingId)) return null; let depth = 1; if (data.parentId) { const parent = await this.prisma.guestCategory.findFirst({ where: { id: data.parentId, weddingId, deletedAt: null }, select: { depth: true } }); if (!parent) throw new GuestError('GUEST_CATEGORY_PARENT_NOT_FOUND', 404, 'Guest category parent not found'); if (parent.depth >= 3) throw new GuestError('GUEST_CATEGORY_DEPTH_INVALID', 400, 'Guest category depth cannot exceed three levels'); depth = parent.depth + 1 } return this.prisma.guestCategory.create({ data: { weddingId, name: data.name, depth, sortOrder: data.sortOrder, ...(data.parentId !== undefined ? { parentId: data.parentId } : {}) }, select: categorySelect }) }
  async updateCategory(userId: string, weddingId: string, categoryId: string, data: UpdateCategoryData) { if (!await this.owns(userId, weddingId)) return null; const current = await this.prisma.guestCategory.findFirst({ where: { id: categoryId, weddingId, deletedAt: null }, select: { id: true, depth: true } }); if (!current) return null; let depth = current.depth; if (data.parentId !== undefined) { if (data.parentId === categoryId) throw new GuestError('GUEST_CATEGORY_CYCLE', 400, 'A category cannot be its own parent'); if (data.parentId === null) depth = 1; else { const parent = await this.prisma.guestCategory.findFirst({ where: { id: data.parentId, weddingId, deletedAt: null }, select: { id: true, depth: true, parentId: true } }); if (!parent) throw new GuestError('GUEST_CATEGORY_PARENT_NOT_FOUND', 404, 'Guest category parent not found'); if (parent.depth >= 3) throw new GuestError('GUEST_CATEGORY_DEPTH_INVALID', 400, 'Guest category depth cannot exceed three levels'); depth = parent.depth + 1; let ancestor = parent.parentId; for (let i = 0; i < 3 && ancestor; i += 1) { if (ancestor === categoryId) throw new GuestError('GUEST_CATEGORY_CYCLE', 400, 'Category cycle is not allowed'); ancestor = (await this.prisma.guestCategory.findFirst({ where: { id: ancestor, weddingId }, select: { parentId: true } }))?.parentId ?? null } } } const result = await this.prisma.guestCategory.updateMany({ where: { id: categoryId, weddingId, deletedAt: null }, data: { ...(data.name !== undefined ? { name: data.name } : {}), ...(data.parentId !== undefined ? { parentId: data.parentId } : {}), ...(data.sortOrder !== undefined ? { sortOrder: data.sortOrder } : {}), depth } }); return result.count ? this.prisma.guestCategory.findUnique({ where: { id: categoryId }, select: categorySelect }) : null }
  async deleteCategory(userId: string, weddingId: string, categoryId: string) { if (!await this.owns(userId, weddingId)) return null; const result = await this.prisma.guestCategory.updateMany({ where: { id: categoryId, weddingId, deletedAt: null }, data: { deletedAt: new Date() } }); return result.count === 1 }
  async listGroups(userId: string, weddingId: string) { if (!await this.owns(userId, weddingId)) return null; return this.prisma.guestGroup.findMany({ where: { weddingId, deletedAt: null }, select: groupSelect, orderBy: [{ name: 'asc' }, { id: 'asc' }] }) }
  async createGroup(userId: string, weddingId: string, data: CreateGroupData) { if (!await this.owns(userId, weddingId)) return null; return this.prisma.guestGroup.create({ data: { weddingId, name: data.name, ...(data.note !== undefined ? { note: data.note } : {}) }, select: groupSelect }) }
  async deleteGroup(userId: string, weddingId: string, groupId: string) { if (!await this.owns(userId, weddingId)) return null; const result = await this.prisma.guestGroup.updateMany({ where: { id: groupId, weddingId, deletedAt: null }, data: { deletedAt: new Date() } }); return result.count === 1 }
  async exportOwned(userId: string, weddingId: string): Promise<GuestExportRow[] | null> { if (!await this.owns(userId, weddingId)) return null; const rows = await this.prisma.guest.findMany({ where: { weddingId, deletedAt: null }, select: { ...guestSelect, group: { select: { name: true } }, category: { select: { name: true, parent: { select: { name: true, parent: { select: { name: true } } } } } } }, orderBy: [{ displayName: 'asc' }, { id: 'asc' }] }); return rows.map((row) => ({ ...row, groupName: row.group?.name ?? null, categoryPath: [row.category?.parent?.parent?.name, row.category?.parent?.name, row.category?.name].filter(Boolean).join(' / ') })) }
  async importOwned(userId: string, weddingId: string, rows: GuestImportRow[]): Promise<GuestExportRow[] | null> { if (!await this.owns(userId, weddingId)) return null; return this.prisma.$transaction(async (tx) => { const result: GuestExportRow[] = []; for (const row of rows) { let categoryId: string | undefined; if (row.categoryPath) { const parts = row.categoryPath.split('/').map((part) => part.trim()).filter(Boolean); if (parts.length > 3) throw new GuestError('GUEST_CATEGORY_DEPTH_INVALID', 400, 'Guest category depth cannot exceed three levels'); let parentId: string | undefined; let parentDepth = 0; for (const name of parts) { const existing = await tx.guestCategory.findFirst({ where: { weddingId, name, parentId: parentId ?? null, deletedAt: null }, select: { id: true, depth: true } }); const category = existing ?? await tx.guestCategory.create({ data: { weddingId, name, depth: parentDepth + 1, ...(parentId ? { parentId } : {}) }, select: { id: true, depth: true } }); categoryId = category.id; parentId = category.id; parentDepth = category.depth } } let groupId: string | undefined; if (row.groupName) { const group = await tx.guestGroup.findFirst({ where: { weddingId, name: row.groupName, deletedAt: null }, select: { id: true } }) ?? await tx.guestGroup.create({ data: { weddingId, name: row.groupName }, select: { id: true } }); groupId = group.id } const existing = await tx.guest.findFirst({ where: { weddingId, deletedAt: null, displayName: row.displayName, ...(row.phone ? { phone: row.phone } : {}) }, select: { id: true } }); const data = { displayName: row.displayName, maxPartySize: row.maxPartySize ?? 1, tags: row.tags ?? [], ...(categoryId ? { categoryId } : {}), ...(groupId ? { groupId } : {}), ...(row.phone !== undefined ? { phone: row.phone } : {}), ...(row.email !== undefined ? { email: row.email } : {}), ...(row.note !== undefined ? { note: row.note } : {}), ...(row.tableName !== undefined ? { tableName: row.tableName } : {}) }; const saved = existing ? await tx.guest.update({ where: { id: existing.id }, data, select: guestSelect }) : await tx.guest.create({ data: { weddingId, ...data }, select: guestSelect }); result.push({ ...saved, categoryPath: row.categoryPath ?? '', groupName: row.groupName ?? null }) } return result }) }
  async createInvitation(userId: string, weddingId: string, data: CreateInvitationData) { if (!await this.owns(userId, weddingId)) return null; const guest = data.guestId ? await this.findOwned(userId, weddingId, data.guestId) : null; if (data.guestId && !guest) return null; const raw = token(); const base = slugBase(guest?.displayName ?? data.label ?? 'guest'); let publicSlug = base; for (let suffix = 2; await this.prisma.invitation.findFirst({ where: { weddingId, publicSlug }, select: { id: true } }); suffix += 1) publicSlug = `${base}-${suffix}`; const invitation = await this.prisma.invitation.create({ data: { weddingId, publicSlug, maxPartySize: data.maxPartySize, tokenHash: tokenHash(raw), ...(data.guestId !== undefined ? { guestId: data.guestId } : {}), ...(data.label !== undefined ? { label: data.label } : {}), ...(data.expiresAt !== undefined ? { expiresAt: data.expiresAt } : {}) }, select: invitationSelect }); return { invitation, token: raw } }
  async rotateInvitation(userId: string, weddingId: string, invitationId: string) { if (!await this.owns(userId, weddingId)) return null; const raw = token(); const result = await this.prisma.invitation.updateMany({ where: { id: invitationId, weddingId, status: 'ACTIVE' }, data: { tokenHash: tokenHash(raw), updatedAt: new Date() } }); if (!result.count) return null; const invitation = await this.prisma.invitation.findUnique({ where: { id: invitationId }, select: invitationSelect }); return invitation ? { invitation, token: raw } : null }
  async revokeInvitation(userId: string, weddingId: string, invitationId: string) { if (!await this.owns(userId, weddingId)) return null; const result = await this.prisma.invitation.updateMany({ where: { id: invitationId, weddingId, status: 'ACTIVE' }, data: { status: 'REVOKED', revokedAt: new Date() } }); return result.count === 1 }
  async resolvePublicInvitation(weddingSlug: string, guestSlug: string): Promise<PublicInvitationView | null> { const row = await this.prisma.invitation.findFirst({ where: { publicSlug: guestSlug, status: 'ACTIVE', wedding: { slug: weddingSlug, status: 'PUBLISHED', deletedAt: null } }, select: { publicSlug: true, maxPartySize: true, expiresAt: true, wedding: { select: { slug: true } }, guest: { select: { displayName: true } } } }); if (!row?.publicSlug || !row.wedding.slug) return null; if (row.expiresAt && row.expiresAt <= new Date()) return null; return { weddingSlug: row.wedding.slug, invitationSlug: row.publicSlug, guestName: row.guest?.displayName ?? null, maxPartySize: row.maxPartySize, expiresAt: row.expiresAt } }
}
