export type RedSpiderLilyMediaOwnership = 'USER_UPLOAD' | 'RENDERER_OWNED'
export type RedSpiderLilyMediaFallback =
  'NEUTRAL_PLACEHOLDER' | 'TEXT_FIRST' | 'STATIC_POSTER' | 'HIDE_MEDIA_KEEP_CONTENT'

export type RedSpiderLilyMediaSlot = {
  sectionKey: string
  field: string
  role: string
  ownership: RedSpiderLilyMediaOwnership
  required: boolean
  minItems: number
  maxItems: number
  aspectRatio: string
  crop: 'cover' | 'contain' | 'natural'
  focalPoint: 'center' | 'top' | 'user_defined'
  fallback: RedSpiderLilyMediaFallback
  mobileBehavior: string
  altTextRequired: boolean
}

export const redSpiderLilyMediaContract = {
  uploadSlots: [
    {
      sectionKey: 'hero',
      field: 'hero.media',
      role: 'hero',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 1,
      aspectRatio: '16:9 or 4:5',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'NEUTRAL_PLACEHOLDER',
      mobileBehavior: 'Use the same focal point with a taller 4:5 crop.',
      altTextRequired: true,
    },
    {
      sectionKey: 'ourStory',
      field: 'ourStory.media',
      role: 'story',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 3,
      aspectRatio: '3:4 or 4:5',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Collapse to one readable image before the story copy.',
      altTextRequired: true,
    },
    {
      sectionKey: 'chapters',
      field: 'chapters[].cover',
      role: 'chapter',
      ownership: 'USER_UPLOAD',
      required: true,
      minItems: 1,
      maxItems: 1,
      aspectRatio: '4:5 or 16:10',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'NEUTRAL_PLACEHOLDER',
      mobileBehavior: 'Keep chapter title/date visible when cover is missing.',
      altTextRequired: true,
    },
    {
      sectionKey: 'moments',
      field: 'moments[].cover',
      role: 'moment',
      ownership: 'USER_UPLOAD',
      required: true,
      minItems: 1,
      maxItems: 1,
      aspectRatio: '1:1, 4:5 or 3:2',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'NEUTRAL_PLACEHOLDER',
      mobileBehavior: 'Use one-column cards without depending on image height.',
      altTextRequired: true,
    },
    {
      sectionKey: 'photoDelivery',
      field: 'photoDelivery.albums',
      role: 'album-source',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 12,
      aspectRatio: 'n/a',
      crop: 'natural',
      focalPoint: 'center',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Expose a full-width readable album CTA.',
      altTextRequired: false,
    },
    {
      sectionKey: 'thankYou',
      field: 'thankYou.media',
      role: 'finale',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 1,
      aspectRatio: '16:9 or 4:5',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Keep the closing message readable without media.',
      altTextRequired: true,
    },
    {
      sectionKey: 'guestbook',
      field: 'guestbook.media',
      role: 'optional-support',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 1,
      aspectRatio: '4:5 or 1:1',
      crop: 'cover',
      focalPoint: 'center',
      fallback: 'HIDE_MEDIA_KEEP_CONTENT',
      mobileBehavior: 'Remove media layer and keep approved wishes.',
      altTextRequired: true,
    },
    {
      sectionKey: 'peopleBehindTheDay',
      field: 'peopleBehindTheDay[].media',
      role: 'people-cover',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 24,
      aspectRatio: '1:1 or 4:5',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Use a horizontal snap rail and keep names readable.',
      altTextRequired: true,
    },
    {
      sectionKey: 'peopleBehindTheDay',
      field: 'peopleBehindTheDay[].gallery',
      role: 'people-gallery',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 12,
      aspectRatio: 'natural',
      crop: 'natural',
      focalPoint: 'center',
      fallback: 'HIDE_MEDIA_KEEP_CONTENT',
      mobileBehavior: 'Open the selected item gallery in a lightbox.',
      altTextRequired: true,
    },
    {
      sectionKey: 'weddingFilm',
      field: 'weddingFilm.poster',
      role: 'video-poster',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 1,
      aspectRatio: '16:9',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'STATIC_POSTER',
      mobileBehavior: 'Use poster and native controls; never require autoplay.',
      altTextRequired: true,
    },
    {
      sectionKey: 'soundtrack',
      field: 'soundtrack.cover',
      role: 'audio-cover',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 1,
      aspectRatio: '1:1',
      crop: 'cover',
      focalPoint: 'center',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Keep audio control usable without cover art.',
      altTextRequired: true,
    },
    {
      sectionKey: 'behindTheScenes',
      field: 'behindTheScenes[].media',
      role: 'behind-the-scenes-cover',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 24,
      aspectRatio: '3:2, 4:5 or 9:16',
      crop: 'cover',
      focalPoint: 'user_defined',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Use a horizontal snap rail and ordered mobile fallback.',
      altTextRequired: true,
    },
    {
      sectionKey: 'behindTheScenes',
      field: 'behindTheScenes[].gallery',
      role: 'behind-the-scenes-gallery',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 12,
      aspectRatio: 'natural',
      crop: 'natural',
      focalPoint: 'center',
      fallback: 'HIDE_MEDIA_KEEP_CONTENT',
      mobileBehavior: 'Open the selected item gallery in a lightbox.',
      altTextRequired: true,
    },
    {
      sectionKey: 'memoryCapsule',
      field: 'memoryCapsule.media',
      role: 'capsule',
      ownership: 'USER_UPLOAD',
      required: false,
      minItems: 0,
      maxItems: 1,
      aspectRatio: '4:5 or 3:2',
      crop: 'cover',
      focalPoint: 'center',
      fallback: 'TEXT_FIRST',
      mobileBehavior: 'Prioritize the message over the image.',
      altTextRequired: true,
    },
  ] satisfies RedSpiderLilyMediaSlot[],
  rendererOwned: [
    'botanical-frame',
    'red-spider-lily-ornament',
    'paper-grain',
    'chapter-divider',
    'light-leak',
    'ambient-petal-or-dust',
  ],
  albumSource: {
    supported: ['INTERNAL_ALBUM', 'EXTERNAL_ALBUM_LINK'] as const,
    external: {
      hrefRequired: true,
      labelRequired: true,
      validateProtocol: ['https:'] as const,
      defaultTarget: '_blank' as const,
      rel: 'noreferrer' as const,
      invalidState:
        'Show a clear unavailable-album message and keep the photo-delivery content visible.',
    },
    internal: {
      albumIdRequired: true,
      galleryOwnsDownload: true,
      mobileGesture: 'swipe',
    },
  },
  independenceAudit: {
    replacementSet: [
      'neutral-portrait',
      'landscape-family',
      'dark-reception',
      'bright-outdoor',
      'no-media',
    ],
    identityMustRemainIn: [
      'palette',
      'typography',
      'layout',
      'frame',
      'texture',
      'divider',
      'renderer-owned-botanical-decor',
    ],
    forbiddenDependencies: [
      'sample-couple-as-theme-background',
      'sample-photo-specific-crop',
      'photo-color-as-only-accent',
      'hard-coded-gallery-count',
    ],
  },
} as const
