import { ArrowDown, ArrowUp, ArrowUpRight, CaretRight, Flower, ImagesSquare } from '@phosphor-icons/react'
import type { RedSpiderLilyMedia, RedSpiderLilyOptionalContent, RedSpiderLilyRecapContent } from './content'
import { redSpiderLilyRecapFixture } from './fixture'
import './red-spider-lily.css'

function MediaFrame({ media, className = '' }: { media?: RedSpiderLilyMedia; className?: string }) {
  return media?.src ? <img className={className} src={media.src} alt={media.alt} /> : <div className={`rsl-media-placeholder ${className}`} role="img" aria-label={media?.alt ?? 'Khu vực ảnh của album'}><Flower weight="thin" /></div>
}

function OptionalSection({ sectionKey, content }: { sectionKey: string; content: RedSpiderLilyOptionalContent }) {
  if (!content.enabled) return null
  return <section className="rsl-optional-section" data-editor-section={sectionKey}><p className="rsl-eyebrow">Ký ức thêm</p><h2>{content.title}</h2><p>{content.body}</p></section>
}

export function RedSpiderLilyRecap({ data = redSpiderLilyRecapFixture.content }: { data?: RedSpiderLilyRecapContent }) {
  return <main className="red-spider-lily-recap">
    <section className="rsl-hero" data-editor-section="hero"><div className="rsl-hero-wash" aria-hidden="true" /><div className="rsl-hero-stem" aria-hidden="true"><i /><i /><i /></div><div className="rsl-hero-media"><MediaFrame media={data.hero.media} /></div><div className="rsl-hero-content"><p className="rsl-eyebrow">Wedding memories</p><p className="rsl-date">{data.hero.date}{data.hero.place ? `  ·  ${data.hero.place}` : ''}</p><h1>{data.hero.couple}</h1><p className="rsl-hero-tagline">{data.hero.tagline}</p><a className="rsl-text-link" href="#rsl-story">{data.hero.ctaLabel}<ArrowDown size={16} /></a></div><span className="rsl-hero-mark" aria-hidden="true">01</span></section>
    <section id="rsl-story" className="rsl-story" data-editor-section="ourStory"><div className="rsl-section-intro"><p className="rsl-eyebrow">{data.ourStory.eyebrow}</p><h2>{data.ourStory.title}</h2></div><div className="rsl-story-copy"><p>{data.ourStory.body}</p>{data.ourStory.quote ? <blockquote>“{data.ourStory.quote}”</blockquote> : null}</div><div className="rsl-story-media">{data.ourStory.media.length ? data.ourStory.media.map((media) => <MediaFrame key={media.alt} media={media} />) : <MediaFrame media={{ src: '', alt: 'Ảnh lời dẫn', role: 'story' }} />}</div></section>
    <section className="rsl-chapters" data-editor-section="chapters"><div className="rsl-chapters-head"><div><p className="rsl-eyebrow">Những chương đã qua</p><h2>Đi qua từng ngày<br /><em>đã làm nên chúng mình.</em></h2></div><span className="rsl-section-index">03 / 06</span></div><div className="rsl-chapter-list">{data.chapters.map((chapter, index) => <article className="rsl-chapter" key={chapter.id}><div className="rsl-chapter-number">0{index + 1}</div><MediaFrame media={chapter.cover} className="rsl-chapter-image" /><div className="rsl-chapter-copy"><p className="rsl-eyebrow">{chapter.dateLabel}</p><h3>{chapter.title}</h3><p>{chapter.description}</p>{chapter.album ? <a className="rsl-text-link" href={chapter.album.type === 'EXTERNAL_ALBUM_LINK' ? chapter.album.href : '#rsl-photo-delivery'}>{chapter.album.type === 'EXTERNAL_ALBUM_LINK' ? chapter.album.label : 'Xem kỷ niệm'}<ArrowUpRight size={15} /></a> : null}</div></article>)}</div></section>
    <section className="rsl-moments" data-editor-section="moments"><div className="rsl-moments-heading"><p className="rsl-eyebrow">Những khoảnh khắc</p><h2>Điều chúng mình<br /><em>sẽ luôn nhớ.</em></h2><p>Những nhóm ký ức nhỏ làm ngày hôm ấy trở nên thật riêng.</p></div><div className="rsl-moment-grid">{data.moments.map((moment, index) => <article className={`rsl-moment rsl-moment-${index + 1}`} key={moment.id}><MediaFrame media={moment.cover} className="rsl-moment-image" /><div className="rsl-moment-copy"><span>0{index + 1}</span><h3>{moment.title}</h3><p>{moment.description}</p><a className="rsl-icon-link" href={moment.album?.type === 'EXTERNAL_ALBUM_LINK' ? moment.album.href : '#rsl-photo-delivery'} aria-label={`Xem album ${moment.title}`}><CaretRight size={18} /></a></div></article>)}</div></section>
    <section id="rsl-photo-delivery" className="rsl-delivery" data-editor-section="photoDelivery"><div className="rsl-delivery-seal" aria-hidden="true"><ImagesSquare weight="thin" /></div><div><p className="rsl-eyebrow">{data.photoDelivery.eyebrow}</p><h2>{data.photoDelivery.title}</h2><p>{data.photoDelivery.body}</p></div><a className="rsl-solid-link" href={data.photoDelivery.albums[0]?.type === 'EXTERNAL_ALBUM_LINK' ? data.photoDelivery.albums[0].href : '#rsl-photo-delivery'}>{data.photoDelivery.ctaLabel}<ArrowUpRight size={17} /></a></section>
    <OptionalSection sectionKey="guestbook" content={data.optional.guestbook} /><OptionalSection sectionKey="peopleBehindTheDay" content={data.optional.peopleBehindTheDay} /><OptionalSection sectionKey="weddingFilm" content={data.optional.weddingFilm} /><OptionalSection sectionKey="soundtrack" content={data.optional.soundtrack} /><OptionalSection sectionKey="behindTheScenes" content={data.optional.behindTheScenes} /><OptionalSection sectionKey="memoryCapsule" content={data.optional.memoryCapsule} />
    <section className="rsl-thank-you" data-editor-section="thankYou"><div className="rsl-thank-you-image"><MediaFrame media={data.thankYou.media} /></div><div className="rsl-thank-you-copy"><p className="rsl-eyebrow">Lời cảm ơn</p><h2>{data.thankYou.title}</h2><p>{data.thankYou.body}</p><strong>{data.thankYou.signature}</strong><small>{data.thankYou.date}</small></div></section><footer className="rsl-footer"><span>{data.thankYou.signature}</span><span>{data.thankYou.date}</span><a href="#top" aria-label="Về đầu trang"><ArrowUp size={17} /></a></footer>
  </main>
}
