import { redSpiderLilyMediaContract } from './media-contract'

const requiredSections = ['hero', 'ourStory', 'chapters', 'moments', 'photoDelivery', 'thankYou'] as const
const optionalSections = ['guestbook', 'peopleBehindTheDay', 'weddingFilm', 'soundtrack', 'behindTheScenes', 'memoryCapsule'] as const
const sectionLabels = {
  hero: 'Trang bia recap',
  ourStory: 'Loi dan',
  chapters: 'Cac chuong ky uc',
  moments: 'Nhung khoanh khac',
  photoDelivery: 'Tra anh',
  thankYou: 'Loi cam on',
  guestbook: 'Loi chuc o lai',
  peopleBehindTheDay: 'Nhung nguoi phia sau',
  weddingFilm: 'Thuoc phim ngay cuoi',
  soundtrack: 'Am thanh cua ky uc',
  behindTheScenes: 'Phia sau canh hoa',
  memoryCapsule: 'Chuong tiep theo',
} as const
const sectionLayoutOptions = {
  hero: ['cinematic-cover', 'layered-album-cover'],
  ourStory: ['editorial-three-column', 'quote-and-memory-stack'],
  chapters: ['vertical-editorial-timeline', 'chapter-album-rail'],
  moments: ['css-3d-coverflow', 'editorial-filmstrip'],
  photoDelivery: ['album-portal-row', 'album-index-grid'],
  thankYou: ['two-panel-album-back-cover', 'cinematic-closing-card'],
  guestbook: ['curated-wish-wall', 'polaroid-notes'],
  peopleBehindTheDay: ['repeatable-portrait-rail', 'credit-gallery-grid'],
  weddingFilm: ['cinematic-film-feature', 'poster-and-copy'],
  soundtrack: ['vinyl-player-story', 'audio-memory-card'],
  behindTheScenes: ['four-card-window-rail', 'contact-sheet-slider'],
  memoryCapsule: ['letter-and-image-close', 'future-note-gallery'],
} as const
const sectionMediaRoles = {
  hero: ['hero'],
  ourStory: ['story'],
  chapters: ['chapter', 'gallery'],
  moments: ['moment', 'gallery'],
  photoDelivery: ['internal-album', 'external-album-link'],
  thankYou: ['finale'],
  guestbook: ['guestbook'],
  peopleBehindTheDay: ['person', 'gallery'],
  weddingFilm: ['video-poster'],
  soundtrack: ['soundtrack'],
  behindTheScenes: ['behind-the-scenes', 'gallery'],
  memoryCapsule: ['capsule', 'gallery'],
} as const
const repeatableSectionRules = {
  chapters: { repeatable: true, minItems: 1, maxItems: 12, itemMediaField: 'cover', maxMediaPerItem: 1, interaction: 'editorial-timeline' },
  moments: { repeatable: true, minItems: 1, maxItems: 12, itemMediaField: 'cover', maxMediaPerItem: 1, interaction: 'asymmetric-grid' },
  peopleBehindTheDay: { repeatable: true, minItems: 0, maxItems: 24, itemMediaField: 'media', galleryField: 'gallery', maxMediaPerItem: 12, interaction: 'horizontal-snap-rail-lightbox' },
  behindTheScenes: { repeatable: true, minItems: 0, maxItems: 24, itemMediaField: 'media', galleryField: 'gallery', maxMediaPerItem: 12, interaction: 'horizontal-snap-rail-lightbox' },
} as const

export const redSpiderLilyRecapTemplateConfig = {
  templateKey: 'red-spider-lily-recap',
  displayName: 'Dấu Son Bỉ Ngạn',
  productType: 'WEDDING_RECAP',
  templateVersion: '0.1.0',
  templateConfigVersion: 1,
  contentSchemaVersion: 1,
  rendererApiVersion: 1,
  status: 'draft',
  type: 'recap',
  description: 'Wedding recap editorial về những ký ức còn nở lại sau ngày cưới.',
  previewPath: '/templates/recaps/red-spider-lily/preview',
  capabilities: { seo: true, share: true, download: true, externalAlbumLinks: true, soundtrack: true, weddingFilm: true },
  theme: {
    palettes: ['vermilion-paper', 'ink-ivory'],
    default: { palette: 'vermilion-paper', motionLevel: 'EXPRESSIVE', galleryStyle: 'editorial-album-portal' },
    identity: ['red-spider-lily', 'paper-grain', 'botanical-frame', 'chapter-bloom', 'floating-decor-set'],
    artworkManifest: [
      { file: 'red-spider-lily-botanical-cluster.png', role: 'organic-floating-decor', sections: ['hero', 'peopleBehindTheDay', 'behindTheScenes', 'thankYou'] },
      { file: 'red-spider-lily-vow-prop.png', role: 'vow-supporting-prop', sections: ['ourStory', 'guestbook', 'memoryCapsule'] },
      { file: 'red-spider-lily-petal-sprite.png', role: 'ambient-sprite-source-only', sections: ['backgroundAtmosphere'] },
      { file: 'red-spider-lily-ring-prop-v2.png', role: 'ring-standalone-prop', sections: ['chapters', 'photoDelivery', 'soundtrack'] },
      { file: 'red-spider-lily-film-ribbon-v2.png', role: 'film-ribbon-divider', sections: ['moments', 'weddingFilm', 'behindTheScenes'] },
      { file: 'red-spider-lily-divider-thread-v2.png', role: 'section-transition-divider', sections: ['ourStory', 'chapters', 'peopleBehindTheDay', 'thankYou'] },
      { file: 'red-spider-lily-light-leak-v2.png', role: 'light-atmosphere-overlay', sections: ['hero', 'photoDelivery', 'weddingFilm', 'memoryCapsule'] },
      { file: 'red-spider-lily-topdown-bloom.png', role: 'top-down-floating-bloom', sections: ['hero', 'photoDelivery', 'behindTheScenes'] },
    ],
  },
  mediaContract: redSpiderLilyMediaContract,
  composition: {
    order: ['hero', 'ourStory', 'chapters', 'moments', 'photoDelivery', 'optional', 'thankYou'],
    layouts: {
      hero: 'full-viewport-cover',
      ourStory: 'editorial-three-column',
      chapters: 'vertical-editorial-timeline',
      moments: 'asymmetric-dark-feature-grid',
      photoDelivery: 'album-portal-row',
      guestbook: 'curated-wish-wall',
      peopleBehindTheDay: 'portrait-credit-grid',
      weddingFilm: 'cinematic-film-feature',
      soundtrack: 'vinyl-player-story',
      behindTheScenes: 'staggered-contact-sheet',
      memoryCapsule: 'letter-and-image-close',
      thankYou: 'two-panel-album-back-cover',
    },
    transitions: {
      heroToOurStory: 'ink-to-ivory-thread',
      ourStoryToChapters: 'paper-divider',
      chaptersToMoments: 'paper-to-deep-vermilion',
      momentsToPhotoDelivery: 'deep-vermilion-to-ivory',
      optionalToThankYou: 'muted-band-to-ink-close',
    },
    responsive: {
      desktop: 'asymmetric-editorial',
      tablet: 'reduced-columns',
      mobile: 'single-column-native-scroll',
      reducedMotion: 'static-composition',
    },
  },
  sections: [
    ...requiredSections.map((sectionKey, index) => ({ sectionKey, label: sectionLabels[sectionKey], required: true, canToggle: false, canReorder: index > 0 && index < requiredSections.length - 1, layouts: sectionLayoutOptions[sectionKey], defaultLayout: sectionLayoutOptions[sectionKey][0], mediaRoles: sectionMediaRoles[sectionKey], ...(repeatableSectionRules[sectionKey as keyof typeof repeatableSectionRules] ?? { repeatable: false }) })),
    ...optionalSections.map((sectionKey) => ({ sectionKey, label: sectionLabels[sectionKey], required: false, canToggle: true, canReorder: true, defaultEnabled: false, layouts: sectionLayoutOptions[sectionKey], defaultLayout: sectionLayoutOptions[sectionKey][0], mediaRoles: sectionMediaRoles[sectionKey], ...(repeatableSectionRules[sectionKey as keyof typeof repeatableSectionRules] ?? { repeatable: false }) })),
  ],
  authoring: {
    phase: 5,
    phase1Artifact: 'docs/frontend/wedding-recaps/red-spider-lily-phase-1.md',
    phase2Artifact: 'docs/frontend/wedding-recaps/red-spider-lily-phase-2.md',
    phase3Artifact: 'docs/frontend/wedding-recaps/red-spider-lily-phase-3.md',
    phase4Artifact: 'docs/frontend/wedding-recaps/red-spider-lily-phase-4.md',
    phase5Artifact: 'docs/frontend/wedding-recaps/red-spider-lily-phase-5.md',
    requiredSections,
    optionalSections,
    primaryLanguage: 'vi',
    maxEnglishQuotes: 3,
    mediaIndependent: true,
    designRead: 'Post-wedding digital album with botanical-editorial memory chapters.',
    signatureDirection: 'A renderer-owned red spider lily thread that connects the album chapters.',
  },
} as const
