import type { TemplateConfig, TemplateSectionConfig } from '../../template-config'
import { aureliaCourtFixture } from './fixture'

const text = (label: string, contentKey: string, required = false) => ({ type: 'string' as const, label, contentKey, ...(required ? { required: true } : {}) })
const longText = (label: string, contentKey: string) => ({ type: 'text' as const, label, contentKey, maxLength: 600 })
const image = (label: string, contentKey: string, mediaRole: string) => ({ type: 'image' as const, label, contentKey, mediaRole, mediaValue: 'object' as const })
type Section = Exclude<TemplateSectionConfig, string>

const sections: Section[] = [
  { sectionKey: 'opening', label: 'Mở thiệp', required: true, canToggle: false, canReorder: false, fields: { eyebrow: text('Dòng giới thiệu mở thiệp', 'opening.eyebrow'), title: text('Tiêu đề mở thiệp', 'opening.title') } },
  { sectionKey: 'cover', label: 'Bìa thiệp', required: true, canToggle: false, canReorder: false, fields: { brideName: text('Tên cô dâu', 'couple.brideName', true), groomName: text('Tên chú rể', 'couple.groomName', true), weddingDate: text('Ngày cưới', 'event.weddingDate', true), eyebrow: text('Dòng giới thiệu bìa', 'cover.eyebrow'), title: text('Tiêu đề bìa', 'cover.title'), message: longText('Lời nhắn bìa thiệp', 'cover.message') } },
  { sectionKey: 'families', label: 'Hai bên gia đình', required: true, canToggle: false, canReorder: false, fields: { title: text('Tiêu đề hai gia đình', 'families.title'), subtitle: text('Dòng phụ hai gia đình', 'families.subtitle'), message: longText('Lời nhắn hai gia đình', 'families.message'), brideFather: text('Tên bố cô dâu', 'families.brideSide.father'), brideMother: text('Tên mẹ cô dâu', 'families.brideSide.mother'), brideAddress: text('Địa chỉ gia đình cô dâu', 'families.brideSide.address'), groomFather: text('Tên bố chú rể', 'families.groomSide.father'), groomMother: text('Tên mẹ chú rể', 'families.groomSide.mother'), groomAddress: text('Địa chỉ gia đình chú rể', 'families.groomSide.address') } },
  { sectionKey: 'eventDetails', label: 'Thông tin ngày cưới', required: true, canToggle: false, canReorder: false, fields: { title: text('Nội dung nghi lễ', 'eventDetails.title'), message: text('Thời gian nghi lễ', 'eventDetails.message'), brideTitle: text('Danh xưng cô dâu', 'eventDetails.brideTitle'), groomTitle: text('Danh xưng chú rể', 'eventDetails.groomTitle') } },
  { sectionKey: 'invitation', label: 'Lời báo hỷ', required: true, canToggle: false, canReorder: false, fields: { message: longText('Nội dung lời báo hỷ', 'invitation.message') } },
  { sectionKey: 'venue', label: 'Địa điểm và bản đồ', required: true, canToggle: false, canReorder: true, fields: { title: text('Tiêu đề địa điểm', 'venue.title'), name: text('Tên địa điểm', 'venue.name', true), address: text('Địa chỉ', 'venue.address', true), message: longText('Lời nhắn địa điểm', 'venue.message'), mapUrl: { type: 'url' as const, label: 'Đường dẫn bản đồ', contentKey: 'venue.mapUrl' }, calendarUrl: { type: 'url' as const, label: 'Đường dẫn thêm lịch', contentKey: 'venue.calendarUrl' } } },
  { sectionKey: 'countdown', label: 'Đếm ngược ngày cưới', canToggle: true, canReorder: true, fields: {} },
  { sectionKey: 'timeline', label: 'Lịch trình trong ngày', canToggle: true, canReorder: true, fields: { title: text('Tiêu đề lịch trình', 'timeline.title'), message: longText('Mô tả lịch trình', 'timeline.message'), items: { type: 'items' as const, contentKey: 'timeline.items', label: 'Các mốc thời gian', maxItems: 10, itemFields: { time: { type: 'time' as const, label: 'Thời gian', required: true }, title: { type: 'string' as const, label: 'Tiêu đề mốc thời gian', required: true }, detail: { type: 'text' as const, label: 'Mô tả mốc thời gian' } } } } },
  { sectionKey: 'activities', label: 'Hoạt động trong tiệc', canToggle: true, canReorder: true, fields: { title: text('Tiêu đề hoạt động', 'activities.title'), message: longText('Mô tả hoạt động', 'activities.message'), items: { type: 'items' as const, contentKey: 'activities.items', label: 'Các hoạt động', maxItems: 10, itemFields: { title: { type: 'string' as const, label: 'Tên hoạt động' }, image: image('Ảnh hoạt động', 'image', 'activity') } } } },
  { sectionKey: 'gallery', label: 'Album ảnh', canToggle: true, canReorder: true, fields: { title: text('Tiêu đề album', 'gallery.title'), message: longText('Mô tả album', 'gallery.message'), images: { type: 'images' as const, label: 'Ảnh trong album', contentKey: 'gallery.images', mediaRole: 'gallery', mediaValue: 'object' as const, maxItems: 12 } } },
  { sectionKey: 'rsvp', label: 'Xác nhận tham dự', canToggle: true, canReorder: true, fields: { title: text('Tiêu đề xác nhận tham dự', 'rsvp.title'), message: longText('Lời nhắn xác nhận tham dự', 'rsvp.message'), deadline: text('Hạn phản hồi', 'rsvp.deadline') } },
  { sectionKey: 'guestbook', label: 'Gửi lời chúc', canToggle: true, canReorder: true, fields: { title: text('Tiêu đề gửi lời chúc', 'guestbook.title'), message: longText('Lời nhắn gửi lời chúc', 'guestbook.message') } },
  { sectionKey: 'gift', label: 'Thông tin mừng cưới', canToggle: true, canReorder: true, fields: { title: text('Tiêu đề mừng cưới', 'gift.title'), message: longText('Lời nhắn mừng cưới', 'gift.message'), thankYouMessage: longText('Lời cảm ơn mừng cưới', 'gift.thankYouMessage'), qrMedia: { ...image('Mã QR mừng cưới', 'gift.qrMedia', 'gift-qr'), mediaValue: 'object' as const } } },
  { sectionKey: 'music', label: 'Nhạc nền', canToggle: true, canReorder: false, fields: { trackName: text('Tên hiển thị nhạc nền', 'music.trackName'), backgroundMusicUrl: { type: 'audio' as const, label: 'Tệp nhạc nền', contentKey: 'music.backgroundMusicUrl', audioNameKey: 'music.backgroundMusicName' }, backgroundMusicAutoplay: { type: 'boolean' as const, label: 'Tự động phát sau khi mở thiệp', contentKey: 'music.backgroundMusicAutoplay', default: false } } },
  { sectionKey: 'footer', label: 'Lời cảm ơn cuối thiệp', required: true, canToggle: false, canReorder: false, fields: { title: text('Tiêu đề cuối thiệp', 'footer.title'), message: longText('Lời nhắn cuối thiệp', 'footer.message'), backgroundMedia: image('Ảnh nền cuối thiệp', 'footer.backgroundMedia', 'footer-background') } },
]

export const aureliaCourtTemplateConfig = {
  templateKey: 'aurelia-court', displayName: 'Aurelia Court', templateVersion: '0.1.0', templateConfigVersion: '1.0', contentSchemaVersion: '1.0', rendererApiVersion: '1.0', status: 'ready', productType: 'ONLINE_INVITATION', type: 'invitation', previewPath: '/templates/invitations/aurelia-court/preview',
  quickEdit: [{ contentKey: 'couple.brideName', label: 'Tên cô dâu' }, { contentKey: 'couple.groomName', label: 'Tên chú rể' }, { contentKey: 'event.weddingDate', label: 'Ngày cưới' }], palettes: [{ key: 'aurelia-court', label: 'Ivory champagne', default: true }], defaultData: aureliaCourtFixture,
  capabilities: { commonRsvp: true, guestbook: true, gallery: true, calendar: true, maps: true, gift: true, backgroundMusic: true, reducedMotion: true }, sections,
  theme: { identity: ['aurelia-court', 'royal-stationery', 'champagne-ranunculus', 'ivory-paper'], default: { palette: 'aurelia-court', motionLevel: 'EXPRESSIVE', galleryStyle: 'framed-stationery' }, artworkManifest: 'ASSET_MANIFEST.md' },
  composition: { defaultLayout: 'mobile-royal-stationery-scroll', layouts: { opening: 'gatefold-card', cover: 'royal-cover-card', invitation: 'letter-sheet', families: 'dual-family-panels', eventDetails: 'date-diptych', countdown: 'calendar-countdown', timeline: 'ceremony-route', venue: 'venue-stationery-card', activities: 'framed-activity-stack', gallery: 'stationery-gallery', rsvp: 'reply-card', guestbook: 'wish-card', gift: 'sealed-gift-card', music: 'music-dock', footer: 'closing-seal' }, mobileFallback: 'native-vertical-scroll' },
} as const satisfies TemplateConfig
