import type { TemplateConfig, TemplateFieldConfig, TemplateSectionConfig } from '../../template-config'
import { astralVowFixture } from './fixture'

const text = (label: string, contentKey: string, required = false) => ({ type: 'string' as const, label, contentKey, ...(required ? { required: true } : {}) })
const optional = (sectionKey: string, label: string, fields: Record<string, TemplateFieldConfig> = {}) => ({ sectionKey, label, canToggle: true, canReorder: true, fields })
const astralVowDefaultData = { ...astralVowFixture }
type AstralSectionConfig = Exclude<TemplateSectionConfig, string>
const astralVowSections: AstralSectionConfig[] = [
  { sectionKey: 'opening', label: 'Mở thiệp', required: true, canToggle: false, canReorder: false, fields: { title: text('Tiêu đề mở thiệp', 'opening.title'), message: text('Lời nhắn', 'opening.message') } },
  { sectionKey: 'cover', label: 'Bìa thiệp', required: true, canToggle: false, canReorder: false, fields: { brideName: text('Tên cô dâu', 'couple.brideName', true), groomName: text('Tên chú rể', 'couple.groomName', true), weddingDate: text('Ngày cưới', 'event.weddingDate', true), eyebrow: text('Dòng giới thiệu', 'cover.eyebrow'), title: text('Tiêu đề bìa', 'cover.title') } },
  { sectionKey: 'invitation', label: 'Lời mời', required: true, canToggle: false, canReorder: false, editorLayout: 'invitation-three-column-media', fields: { message: { type: 'text' as const, label: 'Nội dung lời mời', contentKey: 'invitation.message', maxLength: 500 }, invitationMemoryImage1: { type: 'image' as const, label: 'Ảnh kỷ niệm 1', contentKey: 'invitationMemoryImage1', mediaRole: 'invitation-memory', mediaValue: 'object' as const }, invitationMemoryImage2: { type: 'image' as const, label: 'Ảnh kỷ niệm 2', contentKey: 'invitationMemoryImage2', mediaRole: 'invitation-memory', mediaValue: 'object' as const }, invitationMemoryImage3: { type: 'image' as const, label: 'Ảnh kỷ niệm 3', contentKey: 'invitationMemoryImage3', mediaRole: 'invitation-memory', mediaValue: 'object' as const } } },
  { sectionKey: 'families', label: 'Thông tin hai gia đình', required: true, canToggle: false, canReorder: false, fields: { title: text('Tiêu đề', 'families.title'), subtitle: text('Dòng phụ', 'families.subtitle') } },
    { sectionKey: 'countdown', label: 'Đếm ngược ngày vui', canToggle: true, canReorder: true, emptyMessage: 'Đếm ngược sẽ tự lấy ngày và giờ cưới trong thông tin sự kiện.', fields: {} },
  optional('venue', 'Địa điểm và bản đồ', { title: text('Tiêu đề địa điểm', 'venue.title'), name: text('Tên địa điểm', 'venue.name', true), address: text('Địa chỉ', 'venue.address', true), message: { type: 'text' as const, label: 'Lời nhắn địa điểm', contentKey: 'venue.message', maxLength: 240 }, mapUrl: { type: 'url' as const, contentKey: 'venue.mapUrl', label: 'Đường dẫn bản đồ' } }),
  optional('timeline', 'Lịch trình trong ngày', { title: text('Tiêu đề lịch trình', 'timeline.title'), message: { type: 'text' as const, label: 'Mô tả lịch trình', contentKey: 'timeline.message', maxLength: 240 }, items: { type: 'items' as const, contentKey: 'timeline.items', label: 'Các mốc thời gian', recommendedMinItems: 3, maxItems: 10, itemFields: { time: { type: 'time' as const, label: 'Thời gian', required: true }, title: { type: 'string' as const, label: 'Tiêu đề', required: true, maxLength: 80 }, description: { type: 'text' as const, label: 'Mô tả', maxLength: 240 } } } }),
  optional('gallery', 'Album ảnh', { title: text('Tiêu đề album', 'gallery.title'), message: { type: 'text' as const, label: 'Mô tả album', contentKey: 'gallery.message', maxLength: 240 }, images: { type: 'images' as const, contentKey: 'galleryImages', label: 'Ảnh slide trong album', mediaRole: 'gallery', mediaValue: 'url' as const, maxItems: 12 } }),
  optional('rsvp', 'Xác nhận tham dự', { title: text('Tiêu đề RSVP', 'rsvp.title'), message: { type: 'text' as const, label: 'Lời nhắn RSVP', contentKey: 'rsvp.message', maxLength: 240 }, successMessage: { type: 'text' as const, label: 'Lời cảm ơn sau phản hồi', contentKey: 'rsvp.successMessage', maxLength: 240 } } ),
  optional('guestbook', 'Sổ lưu bút', { title: text('Tiêu đề sổ lưu bút', 'guestbook.title'), message: { type: 'text' as const, label: 'Lời nhắn sổ lưu bút', contentKey: 'guestbook.message', maxLength: 240 }, successMessage: { type: 'text' as const, label: 'Lời cảm ơn sau lời chúc', contentKey: 'guestbook.successMessage', maxLength: 240 } }),
  optional('gift', 'Thông tin mừng cưới', { thankYouMessage: { type: 'text' as const, label: 'Lời cảm ơn', contentKey: 'gift.thankYouMessage', maxLength: 240 }, qrMedia: { type: 'image' as const, label: 'Mã QR mừng cưới', contentKey: 'giftQrMedia', mediaRole: 'gift-qr', mediaValue: 'object' as const } }),
  { sectionKey: 'music', label: 'Nhạc nền', canToggle: true, canReorder: false, fields: { backgroundMusicUrl: { type: 'audio' as const, contentKey: 'music.backgroundMusicUrl', audioNameKey: 'music.backgroundMusicName', label: 'Nhạc nền' } } },
  { sectionKey: 'footer', label: 'Lời cảm ơn cuối thiệp', required: true, canToggle: false, canReorder: false, fields: { title: text('Tiêu đề cuối thiệp', 'footer.title'), message: { type: 'text' as const, label: 'Lời nhắn cuối thiệp', contentKey: 'footer.message', maxLength: 300 }, footerMedia: { type: 'image' as const, label: 'Ảnh nền cuối thiệp', contentKey: 'footerMedia', mediaRole: 'footer', mediaValue: 'object' as const } } },
]

const imageField = (label: string, contentKey: string, mediaRole: string) => ({ type: 'image' as const, label, contentKey, mediaRole, mediaValue: 'object' as const })
const astralVowConfiguredSections = astralVowSections.map((section) => {
  if (section.sectionKey === 'invitation') return { ...section, fields: { ...section.fields, invitationMemoryImage1: imageField('Ảnh kỷ niệm 1', 'invitationMemoryImage1', 'invitation-memory'), invitationMemoryImage2: imageField('Ảnh kỷ niệm 2', 'invitationMemoryImage2', 'invitation-memory'), invitationMemoryImage3: imageField('Ảnh kỷ niệm 3', 'invitationMemoryImage3', 'invitation-memory') } }
  if (section.sectionKey === 'families') return { ...section, fields: { ...section.fields, message: text('Lời nhắn hai gia đình', 'families.message'), brideFatherTitle: text('Danh xưng bố cô dâu', 'families.brideSide.fatherTitle'), brideFather: text('Tên bố cô dâu', 'families.brideSide.father'), brideMotherTitle: text('Danh xưng mẹ cô dâu', 'families.brideSide.motherTitle'), brideMother: text('Tên mẹ cô dâu', 'families.brideSide.mother'), brideAddress: text('Địa chỉ gia đình cô dâu', 'families.brideSide.address'), groomFatherTitle: text('Danh xưng bố chú rể', 'families.groomSide.fatherTitle'), groomFather: text('Tên bố chú rể', 'families.groomSide.father'), groomMotherTitle: text('Danh xưng mẹ chú rể', 'families.groomSide.motherTitle'), groomMother: text('Tên mẹ chú rể', 'families.groomSide.mother'), groomAddress: text('Địa chỉ gia đình chú rể', 'families.groomSide.address') } }
  return section
})

export const astralVowTemplateConfig = {
  templateKey: 'astral-vow', displayName: 'Astral Vow', templateVersion: '1.0.0', templateConfigVersion: '1.0', contentSchemaVersion: '1.0', rendererApiVersion: '1.0', status: 'ready', productType: 'ONLINE_INVITATION', type: 'invitation',
  previewPath: '/templates/invitations/astral-vow/preview',
  quickEdit: [{ contentKey: 'couple.brideName', label: 'Tên cô dâu' }, { contentKey: 'couple.groomName', label: 'Tên chú rể' }, { contentKey: 'event.weddingDate', label: 'Ngày cưới' }], palettes: [{ key: 'astral-vow', label: 'Tinh hà huyền bí', default: true }], defaultData: astralVowDefaultData,
  capabilities: { commonRsvp: true, guestbook: true, gallery: true, calendar: true, maps: true, gift: true, backgroundMusic: true, reducedMotion: false },
  sections: astralVowConfiguredSections,
  theme: { identity: ['astral-vow', 'celestial-invitation', 'midnight-nebula', 'eclipse-seal'], default: { palette: 'astral-vow', motionLevel: 'EXPRESSIVE', galleryStyle: 'constellation-stack' }, artworkManifest: 'ASSET_MANIFEST.md' },
  composition: { defaultLayout: 'mobile-celestial-scroll', layouts: { opening: 'eclipse-envelope-reveal', cover: 'constellation-hero', invitation: 'ornamental-plaque', families: 'dual-orbit-cards', countdown: 'astral-countdown-orbit', timeline: 'orbit-route', venue: 'observatory-card', gallery: 'photo-constellation', rsvp: 'reply-card', guestbook: 'star-note', gift: 'minimal-bank-card', music: 'ambient-player-dock', footer: 'starfall-closing' }, mobileFallback: 'native-vertical-scroll' },
} as const satisfies TemplateConfig
