import type { TemplateConfig } from '../../template-config'
import { roseGardenFixture } from './fixture'

const text = (label: string, contentKey?: string, extra: Record<string, unknown> = {}) => ({
  type: 'string' as const,
  label,
  ...(contentKey ? { contentKey } : {}),
  ...extra,
})

const multiline = (label: string, contentKey: string, maxLength = 600) => ({
  type: 'text' as const,
  label,
  contentKey,
  maxLength,
})

const image = (
  label: string,
  contentKey: string,
  mediaRole: string,
  mediaValue: 'url' | 'object' = 'object',
) => ({
  type: 'image' as const,
  label,
  contentKey,
  mediaRole,
  mediaValue,
})

export const roseGardenTemplateConfig = {
  templateKey: 'rose-garden',
  displayName: 'Rose Garden',
  templateVersion: '0.1.0',
  templateConfigVersion: '1.0',
  contentSchemaVersion: '1.0',
  rendererApiVersion: '1.0',
  status: 'draft',
  productType: 'ONLINE_INVITATION',
  type: 'invitation',
  previewPath: '/templates/invitations/rose-garden/preview',
  quickEdit: [
    { contentKey: 'couple.brideName', label: 'Tên cô dâu' },
    { contentKey: 'couple.groomName', label: 'Tên chú rể' },
    { contentKey: 'event.weddingDate', label: 'Ngày cưới' },
  ],
  palettes: [{ key: 'rose-garden', label: 'Rose Garden', default: true }],
  defaultData: { ...roseGardenFixture },
  capabilities: {
    commonRsvp: true,
    guestbook: true,
    gallery: true,
    calendar: true,
    maps: true,
    gift: true,
    backgroundMusic: true,
    reducedMotion: true,
  },
  theme: {
    identity: ['rose-garden', 'pressed-paper', 'botanical-couture', 'rose-ink'],
    default: {
      palette: 'rose-garden',
      motionLevel: 'EXPRESSIVE',
      galleryStyle: 'botanical-filmstrip',
    },
    artworkManifest: 'ASSET_MANIFEST.md',
  },
  composition: {
    defaultLayout: 'mobile-editorial-scroll',
    layouts: {
      opening: 'layered-paper-gate',
      cover: 'envelope-hero',
      invitation: 'memory-triptych',
      families: 'split-family-letter',
      eventDetails: 'date-stamp',
      countdown: 'quiet-calendar',
      timeline: 'botanical-vertical-path',
      venue: 'address-postcard',
      gallery: 'pressed-photo-rail',
      rsvp: 'reply-card',
      guestbook: 'approved-wishes-ledger',
      gift: 'gift-seal-reveal',
      music: 'ambient-player-dock',
      footer: 'closing-letter',
    },
    mobileFallback: 'native-vertical-scroll',
    reducedMotionFallback: 'static-layered-composition',
  },
  sections: [
    {
      sectionKey: 'opening',
      label: 'Mở thiệp',
      required: true,
      canToggle: false,
      canReorder: false,
      editorLayout: 'two-column-media',
      fields: {
        title: text('Tiêu đề mở thiệp', 'opening.title', { maxLength: 120 }),
        message: multiline('Lời nhắn mở thiệp', 'opening.message', 240),
        backImage: image('Ảnh lớp phía sau', 'openingMediaBack', 'opening-back'),
        frontImage: image('Ảnh lớp phía trước', 'openingMediaFront', 'opening-front'),
      },
    },
    {
      sectionKey: 'cover',
      label: 'Bìa thiệp',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        eyebrow: text('Dòng giới thiệu', 'cover.eyebrow', { maxLength: 80 }),
        title: text('Tiêu đề bìa', 'cover.title', { maxLength: 120 }),
        message: multiline('Lời nhắn bìa', 'cover.message', 300),
        heroMedia: image('Ảnh bìa thiệp', 'heroMedia', 'hero'),
      },
    },
    {
      sectionKey: 'invitation',
      label: 'Lời mời',
      required: true,
      canToggle: false,
      canReorder: false,
      editorLayout: 'three-column-media',
      fields: {
        title: text('Tiêu đề lời mời', 'invitation.title', { maxLength: 160 }),
        message: multiline('Nội dung lời mời', 'invitation.message', 500),
        memoryImage1: image('Ảnh ký ức 1', 'invitationMemoryImage1', 'invitation-memory-1', 'url'),
        memoryImage2: image('Ảnh ký ức 2', 'invitationMemoryImage2', 'invitation-memory-2', 'url'),
        memoryImage3: image('Ảnh ký ức 3', 'invitationMemoryImage3', 'invitation-memory-3', 'url'),
      },
    },
    {
      sectionKey: 'families',
      label: 'Thông tin hai gia đình',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        title: text('Tiêu đề thông tin gia đình', 'families.title', { maxLength: 120 }),
        subtitle: text('Dòng phụ thông tin gia đình', 'families.subtitle', { maxLength: 160 }),
        message: multiline('Lời mời', 'families.message', 300),
        brideLabel: text('Nhãn nhà gái', 'families.brideSide.label', { maxLength: 40 }),
        brideFather: text('Tên ba cô dâu', 'families.brideSide.father', { maxLength: 120 }),
        brideMother: text('Tên mẹ cô dâu', 'families.brideSide.mother', { maxLength: 120 }),
        brideAddress: text('Địa chỉ nhà gái', 'families.brideSide.address', { maxLength: 180 }),
        groomLabel: text('Nhãn nhà trai', 'families.groomSide.label', { maxLength: 40 }),
        groomFather: text('Tên ba chú rể', 'families.groomSide.father', { maxLength: 120 }),
        groomMother: text('Tên mẹ chú rể', 'families.groomSide.mother', { maxLength: 120 }),
        groomAddress: text('Địa chỉ nhà trai', 'families.groomSide.address', { maxLength: 180 }),
      },
    },
    {
      sectionKey: 'eventDetails',
      label: 'Thời gian hôn lễ',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        title: text('Tiêu đề thời gian', 'eventDetails.title', { maxLength: 120 }),
        date: text('Ngày hôn lễ', 'eventDetails.date', { maxLength: 100 }),
        time: text('Giờ hôn lễ', 'eventDetails.time', { maxLength: 100 }),
        message: multiline('Lời nhắn thời gian', 'eventDetails.message', 240),
        calendarUrl: { type: 'url' as const, contentKey: 'eventDetails.calendarUrl', label: 'Đường dẫn thêm vào lịch' },
        eventDetailsMedia: image('Ảnh trang trí thời gian', 'eventDetailsMedia', 'event-details'),
      },
    },
    {
      sectionKey: 'countdown',
      label: 'Đếm ngược ngày vui',
      canToggle: true,
      canReorder: true,
      emptyMessage: 'Đếm ngược sẽ tự lấy từ ngày cưới trong thông tin sự kiện.',
      fields: {},
    },
    {
      sectionKey: 'timeline',
      label: 'Lịch trình trong ngày',
      canToggle: true,
      canReorder: true,
      fields: {
        items: {
          type: 'items' as const,
          contentKey: 'timeline.items',
          label: 'Các mốc thời gian',
          recommendedMinItems: 3,
          maxItems: 10,
          itemFields: {
            time: { type: 'time' as const, label: 'Thời gian', required: true },
            title: text('Tên hoạt động', undefined, { required: true, maxLength: 100 }),
            description: multiline('Mô tả', 'description', 240),
            image: image('Ảnh mốc thời gian', 'image', 'timeline'),
          },
        },
      },
    },
    {
      sectionKey: 'venue',
      label: 'Địa điểm và bản đồ',
      canToggle: true,
      canReorder: true,
      fields: {
        title: text('Tiêu đề địa điểm', 'venue.title', { maxLength: 120 }),
        name: text('Tên địa điểm', 'venue.name', { required: true, maxLength: 160 }),
        address: text('Địa chỉ', 'venue.address', { required: true, maxLength: 240 }),
        mapUrl: { type: 'url' as const, contentKey: 'venue.mapUrl', label: 'Đường dẫn bản đồ' },
        message: multiline('Lời nhắn địa điểm', 'venue.message', 240),
      },
    },
    {
      sectionKey: 'gallery',
      label: 'Album ảnh',
      canToggle: true,
      canReorder: true,
      fields: {
        title: text('Tiêu đề album', 'gallery.title', { maxLength: 120 }),
        message: multiline('Lời nhắn album', 'gallery.message', 240),
        images: {
          type: 'images' as const,
          contentKey: 'galleryImages',
          label: 'Ảnh trong album',
          mediaRole: 'gallery',
          mediaValue: 'url' as const,
          maxItems: 12,
        },
      },
    },
    {
      sectionKey: 'rsvp',
      label: 'Xác nhận tham dự',
      canToggle: true,
      canReorder: true,
      fields: {
        title: text('Tiêu đề RSVP', 'rsvp.title', { maxLength: 160 }),
        message: multiline('Lời nhắn RSVP', 'rsvp.message', 240),
        deadline: text('Hạn phản hồi', 'rsvp.deadline', { maxLength: 60 }),
        successMessage: multiline('Thông báo sau khi gửi RSVP', 'rsvp.successMessage', 240),
        attendingLabel: text('Nhãn sẽ tham dự', 'rsvp.attendingLabel', { maxLength: 80 }),
        notAttendingLabel: text('Nhãn chưa thể tham dự', 'rsvp.notAttendingLabel', { maxLength: 80 }),
      },
    },
    {
      sectionKey: 'guestbook',
      label: 'Sổ lưu bút',
      canToggle: true,
      canReorder: true,
      emptyMessage: 'Section này sẽ lấy lời chúc tự động từ danh sách lời chúc đã duyệt.',
      fields: {
        title: text('Tiêu đề sổ lưu bút', 'guestbook.title', { maxLength: 160 }),
        message: multiline('Lời nhắn sổ lưu bút', 'guestbook.message', 240),
        successMessage: multiline('Thông báo sau khi gửi lời chúc', 'guestbook.successMessage', 240),
      },
    },
    {
      sectionKey: 'gift',
      label: 'Thông tin mừng cưới',
      canToggle: true,
      canReorder: true,
      fields: {
        title: text('Tiêu đề mừng cưới', 'gift.title', { maxLength: 80 }),
        message: multiline('Lời nhắn mừng cưới', 'gift.message', 300),
        thankYouMessage: multiline('Lời cảm ơn', 'gift.thankYouMessage', 300),
        qrMedia: image('Mã QR mừng cưới', 'giftQrMedia', 'gift-qr'),
      },
    },
    {
      sectionKey: 'music',
      label: 'Nhạc nền',
      canToggle: true,
      canReorder: false,
      emptyMessage: 'Nhạc nền sẽ lấy bài hát từ kho nhạc chung của hệ thống.',
      fields: {
        backgroundMusicUrl: {
          type: 'audio' as const,
          contentKey: 'music.backgroundMusicUrl',
          audioNameKey: 'music.backgroundMusicName',
          label: 'Nhạc nền',
        },
        backgroundMusicAutoplay: {
          type: 'boolean' as const,
          contentKey: 'music.backgroundMusicAutoplay',
          label: 'Tự động phát',
          default: false,
        },
      },
    },
    {
      sectionKey: 'footer',
      label: 'Lời cảm ơn cuối thiệp',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        title: text('Tiêu đề cuối thiệp', 'footer.title', { maxLength: 120 }),
        message: multiline('Lời nhắn cuối thiệp', 'footer.message', 300),
        media: image('Ảnh trang trí cuối thiệp', 'footerMedia', 'footer'),
      },
    },
  ],
} as const satisfies TemplateConfig
