import { useDeferredValue, useMemo, useState } from 'react'
import { Bank, CaretDown, Coins, CurrencyCircleDollar, Eye, EyeSlash, Gift, LockKey, MagnifyingGlass, Plus, ShieldCheck, X } from '@phosphor-icons/react'
import { initialGiftEntries, methodLabels, reciprocityLabels, type GiftEntry, type GiftKind, type ReciprocityStatus } from '../model/gift-ledger-data'

const money = new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 })

export function GiftLedgerPage() {
  const [entries, setEntries] = useState(initialGiftEntries)
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState<'all' | ReciprocityStatus>('all')
  const [revealed, setRevealed] = useState(false)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [guestName, setGuestName] = useState('')
  const [amount, setAmount] = useState('')
  const [kind, setKind] = useState<GiftKind>('money')
  const [goldWeight, setGoldWeight] = useState('')
  const [goldType, setGoldType] = useState('Vàng 24K')
  const [giftDescription, setGiftDescription] = useState('')
  const deferredQuery = useDeferredValue(query.trim().toLocaleLowerCase('vi'))
  const filtered = useMemo(() => entries.filter((entry) => (status === 'all' || entry.reciprocity === status) && (!deferredQuery || `${entry.guestName} ${entry.group} ${entry.note ?? ''}`.toLocaleLowerCase('vi').includes(deferredQuery))), [deferredQuery, entries, status])
  const total = entries.reduce((sum, entry) => sum + (entry.amount ?? 0), 0)
  const pending = entries.filter((entry) => entry.reciprocity === 'pending').length
  const detailValid = kind === 'money' ? Number(amount.replace(/\D/g, '')) > 0 : kind === 'gold' ? Number(goldWeight) > 0 : giftDescription.trim().length > 0
  const addEntry = () => { if (!guestName.trim() || !detailValid) return; const base = { id: `gift-${Date.now()}`, guestName: guestName.trim(), initials: guestName.trim().split(/\s+/).slice(-2).map((part) => part[0]).join('').toUpperCase(), group: 'Chưa phân nhóm', receivedAt: 'Hôm nay', reciprocity: 'pending' as const }; const detail = kind === 'money' ? { kind, amount: Number(amount.replace(/\D/g, '')), method: 'cash' as const } : kind === 'gold' ? { kind, goldWeight: Number(goldWeight), goldType, method: 'physical' as const } : { kind, description: giftDescription.trim(), method: 'physical' as const }; setEntries((current) => [{ ...base, ...detail }, ...current]); setGuestName(''); setAmount(''); setGoldWeight(''); setGiftDescription(''); setDialogOpen(false) }

  return <div className="gift-ledger-page">
    <header className="gift-ledger-heading"><div><p className="eyebrow">Chuẩn bị <span>/</span> Sổ tiền mừng</p><h1>Sổ tiền mừng</h1><p>Lưu lại tiền và quà mừng để tiện đối chiếu khi cần.</p></div><button className="button button-primary" type="button" onClick={() => setDialogOpen(true)}><Plus size={18} weight="bold" />Thêm khoản mừng</button></header>
    <div className="gift-privacy"><LockKey size={19} weight="fill" /><div><strong>Dữ liệu riêng tư</strong><span>Chỉ chủ tài khoản có thể xem và chỉnh sửa. Dữ liệu không hiển thị trên website cưới.</span></div><ShieldCheck size={20} /></div>
    <section className="gift-summary" aria-label="Tổng quan sổ tiền mừng"><article className="gift-total"><span>Tổng tiền đã ghi</span><div><strong>{revealed ? money.format(total) : '••••••••••'}</strong><button type="button" aria-pressed={revealed} aria-label={revealed ? 'Ẩn tổng tiền mừng' : 'Hiện tổng tiền mừng'} onClick={() => setRevealed((value) => !value)}>{revealed ? <EyeSlash size={18} /> : <Eye size={18} />}</button></div><small>Không quy đổi vàng và quà hiện vật</small></article><article><span>Khoản đã ghi</span><strong>{entries.length}</strong><small>{entries.filter((entry) => entry.kind === 'money').length} tiền · {entries.filter((entry) => entry.kind === 'gold').length} vàng · {entries.filter((entry) => entry.kind === 'gift').length} quà</small></article><article><span>Chưa mừng lại</span><strong>{pending}</strong><small>Cần tham khảo khi có dịp</small></article></section>
    <section className="panel gift-ledger-panel"><div className="gift-toolbar"><label className="gift-search"><span className="sr-only">Tìm trong sổ tiền mừng</span><MagnifyingGlass size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm theo tên khách, nhóm hoặc ghi chú" /></label><label className="gift-filter"><span className="sr-only">Lọc trạng thái mừng lại</span><select value={status} onChange={(event) => setStatus(event.target.value as 'all' | ReciprocityStatus)}><option value="all">Tất cả trạng thái</option><option value="pending">Chưa mừng lại</option><option value="returned">Đã mừng lại</option><option value="notApplicable">Không áp dụng</option></select><CaretDown size={13} /></label></div>
      {filtered.length ? <><div className="gift-table-wrap"><table className="gift-table" aria-label="Danh sách tiền và quà mừng"><thead><tr><th>Khách mời</th><th>Khoản mừng</th><th>Hình thức</th><th>Ngày nhận</th><th>Trạng thái</th><th>Ghi chú</th></tr></thead><tbody>{filtered.map((entry) => <GiftTableRow key={entry.id} entry={entry} revealed={revealed} />)}</tbody></table></div><div className="gift-mobile-list">{filtered.map((entry) => <GiftCard key={entry.id} entry={entry} revealed={revealed} />)}</div><footer className="gift-footer"><span>Hiển thị {filtered.length} trên {entries.length} khoản mừng</span><span>Sổ ghi chép thủ công · Không đối soát ngân hàng</span></footer></> : <div className="gift-empty"><Gift size={30} /><h2>Không tìm thấy khoản mừng</h2><p>Thử thay đổi từ khóa hoặc trạng thái.</p><button type="button" onClick={() => { setQuery(''); setStatus('all') }}>Xóa bộ lọc</button></div>}
    </section>
    {dialogOpen && <div className="gift-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setDialogOpen(false) }}><div className="gift-dialog" role="dialog" aria-modal="true" aria-labelledby="gift-dialog-title"><header><div><h2 id="gift-dialog-title">Thêm khoản mừng</h2><p>Chọn loại khoản mừng và nhập thông tin tương ứng.</p></div><button type="button" onClick={() => setDialogOpen(false)} aria-label="Đóng"><X size={18} /></button></header><label htmlFor="gift-guest">Tên khách mời</label><input id="gift-guest" autoFocus value={guestName} onChange={(event) => setGuestName(event.target.value)} placeholder="Tìm hoặc nhập tên khách" /><fieldset className="gift-kind-picker"><legend>Loại khoản mừng</legend>{([{ value: 'money', label: 'Tiền', icon: CurrencyCircleDollar }, { value: 'gold', label: 'Vàng', icon: Coins }, { value: 'gift', label: 'Quà', icon: Gift }] as const).map(({ value, label, icon: Icon }) => <label key={value} className={kind === value ? 'is-selected' : ''}><input type="radio" name="gift-kind" value={value} checked={kind === value} onChange={() => setKind(value)} /><Icon size={17} /><span>{label}</span></label>)}</fieldset>{kind === 'money' ? <><label htmlFor="gift-amount">Số tiền (VND)</label><input id="gift-amount" inputMode="numeric" value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="Ví dụ: 1.000.000" /></> : kind === 'gold' ? <div className="gift-dialog-grid"><label>Số lượng (chỉ)<input type="number" min="0.1" step="0.1" value={goldWeight} onChange={(event) => setGoldWeight(event.target.value)} placeholder="Ví dụ: 2" /></label><label>Loại vàng<select value={goldType} onChange={(event) => setGoldType(event.target.value)}><option>Vàng 24K</option><option>Vàng 18K</option><option>Vàng miếng SJC</option><option>Khác</option></select></label></div> : <><label htmlFor="gift-description">Tên hoặc mô tả quà</label><input id="gift-description" value={giftDescription} onChange={(event) => setGiftDescription(event.target.value)} placeholder="Ví dụ: Bộ chăn ga cưới" /></>}<div className="gift-dialog-grid"><label>Hình thức nhận<select key={kind} defaultValue={kind === 'money' ? 'cash' : 'physical'} disabled={kind !== 'money'}><option value="cash">Tiền mặt</option><option value="bank">Chuyển khoản</option><option value="physical">Nhận trực tiếp</option></select></label><label>Ngày nhận<input type="date" defaultValue="2026-07-30" /></label></div><footer><button className="button button-secondary" type="button" onClick={() => setDialogOpen(false)}>Hủy</button><button className="button button-primary" type="button" onClick={addEntry} disabled={!guestName.trim() || !detailValid}><Plus size={17} />Lưu khoản mừng</button></footer></div></div>}
  </div>
}

function entryValue(entry: GiftEntry, revealed: boolean) { if (entry.kind === 'money') return revealed ? money.format(entry.amount ?? 0) : '••••••••'; if (entry.kind === 'gold') return `${entry.goldWeight} chỉ · ${entry.goldType}`; return entry.description }
function GiftTableRow({ entry, revealed }: { entry: GiftEntry; revealed: boolean }) { return <tr><td><Identity entry={entry} /></td><td><span className="gift-value">{entryValue(entry, revealed)}</span></td><td><span className="gift-method">{entry.method === 'bank' ? <Bank size={14} /> : entry.kind === 'gold' ? <Coins size={14} /> : entry.method === 'physical' ? <Gift size={14} /> : <CurrencyCircleDollar size={14} />}{entry.kind === 'gold' ? 'Vàng' : methodLabels[entry.method]}</span></td><td>{entry.receivedAt}</td><td><span className={`gift-reciprocity ${entry.reciprocity}`}>{reciprocityLabels[entry.reciprocity]}</span></td><td><span className="gift-note">{entry.note ?? '—'}</span></td></tr> }
function Identity({ entry }: { entry: GiftEntry }) { return <div className="gift-identity"><i>{entry.initials}</i><span><strong>{entry.guestName}</strong><small>{entry.group}</small></span></div> }
function GiftCard({ entry, revealed }: { entry: GiftEntry; revealed: boolean }) { return <article><header><Identity entry={entry} /><span className="gift-value">{entryValue(entry, revealed)}</span></header><dl><div><dt>Hình thức</dt><dd>{entry.kind === 'gold' ? 'Vàng' : methodLabels[entry.method]}</dd></div><div><dt>Ngày nhận</dt><dd>{entry.receivedAt}</dd></div><div><dt>Trạng thái</dt><dd><span className={`gift-reciprocity ${entry.reciprocity}`}>{reciprocityLabels[entry.reciprocity]}</span></dd></div><div><dt>Ghi chú</dt><dd>{entry.note ?? '—'}</dd></div></dl></article> }
