import { useCallback, useDeferredValue, useEffect, useMemo, useRef, useState } from 'react'
import { ArrowClockwise, Browser, CheckCircle, Code, Eye, FileArrowUp, GearSix, MagnifyingGlass, Plus, WarningCircle, X } from '@phosphor-icons/react'
import { AdminTemplateApiError, adminTemplateApi, type AdminTemplate, type AdminTemplateReviewStatus, type AdminTemplateVersion, type TemplateReleaseBundle } from '../../../shared/api/admin-templates'
import { publicTemplateRoutes } from '../../../shared/config/routes'

type Filter = 'ALL' | AdminTemplateReviewStatus
const labels: Record<AdminTemplateReviewStatus, string> = { PENDING_REVIEW: 'Chờ kiểm duyệt', RELEASED: 'Đã xuất bản', DEPRECATED: 'Ngừng phân phối' }
const previews: Record<string, string> = { 'modern-luxe': publicTemplateRoutes.modernLuxePreview, 'verdant-promise': publicTemplateRoutes.verdantPromisePreview, 'chibi-daydream': publicTemplateRoutes.chibiDaydreamPreview }
const stateOf = (item: AdminTemplate): AdminTemplateReviewStatus => item.versions.some((v) => v.reviewStatus === 'PENDING_REVIEW') ? 'PENDING_REVIEW' : item.versions.some((v) => v.reviewStatus === 'RELEASED') ? 'RELEASED' : 'DEPRECATED'
const dateLabel = (value?: string | null) => value ? new Intl.DateTimeFormat('vi-VN').format(new Date(value)) : '—'
const compatibilityOf = (version: AdminTemplateVersion) => version.compatibility ?? { compatible: version.templateConfigVersion === 1 && version.contentSchemaVersion === 1 && version.rendererApiVersion === 1, issues: version.templateConfigVersion === 1 && version.contentSchemaVersion === 1 && version.rendererApiVersion === 1 ? [] : ['Backend hiện tại chưa trả kết quả kiểm tra tương thích.'], supported: { templateConfigVersion: 1, contentSchemaVersion: 1, rendererApiVersion: 1 } }
const previewOf = (item: AdminTemplate) => { const path = item.versions.find((version) => typeof version.config.previewPath === 'string')?.config.previewPath; return typeof path === 'string' && path.startsWith('/') ? path : previews[item.key] }
const bundleIssues = (bundle: TemplateReleaseBundle, productType: AdminTemplate['productType']) => {
  const issues: string[] = []
  if (bundle.bundleVersion !== 1) issues.push('bundleVersion phải bằng 1.')
  if (!bundle.sourceRevision?.trim()) issues.push('Thiếu sourceRevision.')
  if (!Array.isArray(bundle.templates) || !bundle.templates.length) issues.push('Bundle phải có ít nhất một template.')
  bundle.templates?.forEach((template, index) => {
    if (template.productType !== productType) issues.push(`Template ${index + 1}: productType không đúng kho hiện tại.`)
    if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(template.templateVersion ?? '')) issues.push(`Template ${index + 1}: templateVersion phải là SemVer.`)
    if (!template.config || typeof template.config !== 'object' || Array.isArray(template.config)) issues.push(`Template ${index + 1}: config phải là object.`)
    if (template.templateConfigVersion !== 1 || template.contentSchemaVersion !== 1 || template.rendererApiVersion !== 1) issues.push(`Template ${index + 1}: contract hiện chỉ hỗ trợ Config 1, Content 1 và Renderer 1.`)
  })
  return issues
}

export function AdminTemplatesApiPage({ kind }: { kind: 'invitation' | 'website' }) {
  const productType = kind === 'invitation' ? 'ONLINE_INVITATION' : 'WEDDING_WEBSITE'
  const [items, setItems] = useState<AdminTemplate[]>([]), [pending, setPending] = useState(0), [loading, setLoading] = useState(true)
  const [query, setQuery] = useState(''), [filter, setFilter] = useState<Filter>('ALL'), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [selected, setSelected] = useState<AdminTemplate | null>(null), [preview, setPreview] = useState<AdminTemplate | null>(null), [syncOpen, setSyncOpen] = useState(false), [bundle, setBundle] = useState(''), [working, setWorking] = useState(''), [dialogError, setDialogError] = useState('')
  const deferredQuery = useDeferredValue(query)
  const load = useCallback(async () => { setLoading(true); setError(''); try { const result = await adminTemplateApi.list(productType); setItems(result.items.map((item) => ({ ...item, versions: item.versions.map((version) => ({ ...version, usageCount: version.usageCount ?? 0, recentAudit: version.recentAudit ?? [] })) }))); setPending(result.pendingReviewCount) } catch { setError('Không thể tải kho template. Vui lòng thử lại.') } finally { setLoading(false) } }, [productType])
  useEffect(() => { void load() }, [load])
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(''), 3000); return () => window.clearTimeout(timer) }, [notice])
  useEffect(() => { if (!selected && !syncOpen && !preview) return; const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !working) { setSelected(null); setSyncOpen(false); setPreview(null) } }; document.body.style.overflow = 'hidden'; window.addEventListener('keydown', close); return () => { document.body.style.overflow = ''; window.removeEventListener('keydown', close) } }, [selected, syncOpen, preview, working])
  const visible = useMemo(() => { const value = deferredQuery.trim().toLocaleLowerCase('vi'); return items.filter((item) => (filter === 'ALL' || item.versions.some((v) => v.reviewStatus === filter)) && (!value || `${item.name} ${item.key} ${item.description ?? ''}`.toLocaleLowerCase('vi').includes(value))) }, [deferredQuery, filter, items])
  const count = (status: AdminTemplateReviewStatus) => items.filter((item) => item.versions.some((v) => v.reviewStatus === status)).length
  const lifecycle = async (item: AdminTemplate, version: AdminTemplateVersion, action: 'release' | 'deprecate') => { if (action === 'deprecate' && !window.confirm(`Ngừng phân phối ${item.name} v${version.version}? ${version.usageCount} đám cưới đang dùng vẫn được giữ.`)) return; setWorking(version.id); setDialogError(''); try { if (action === 'release') await adminTemplateApi.release(item.key, version.version); else await adminTemplateApi.deprecate(item.key, version.version); setNotice(action === 'release' ? 'Đã phát hành version.' : 'Đã ngừng phân phối version.'); setSelected(null); await load() } catch (cause) { setDialogError(cause instanceof AdminTemplateApiError && cause.code === 'TEMPLATE_VERSION_INCOMPATIBLE' ? `Chưa thể phát hành: ${cause.message}` : 'Không thể cập nhật trạng thái version. Vui lòng thử lại.') } finally { setWorking('') } }
  const sync = async () => { setWorking('sync'); setDialogError(''); try { const result = await adminTemplateApi.sync(); setNotice('Synchronized ' + result.created + ' new template version(s); ' + result.unchanged + ' unchanged.'); await load() } catch (cause) { setDialogError(cause instanceof AdminTemplateApiError ? cause.message : 'Template sync failed.') } finally { setWorking('') } }
  return <div className="admin-dashboard admin-library-page">
    <header className="admin-page-heading"><div><p>Nội dung & giao diện <span>/</span> Kho giao diện</p><h1>Kho {kind === 'invitation' ? 'thiệp online' : 'website cưới'}</h1><span>Kiểm duyệt, phát hành và quản lý vòng đời template từ dữ liệu hệ thống.</span></div><button className="button button-primary" type="button" disabled={working === 'sync'} onClick={() => void sync()}><Plus /> {working === 'sync' ? 'Đang kiểm tra…' : 'Kiểm tra và đồng bộ'}</button></header>
    <section className="admin-library-summary" aria-label="Tổng quan kho template"><div><span>Tất cả template</span><strong>{items.length}</strong></div><div><span>Đang hoạt động</span><strong>{count('RELEASED')}</strong><small className="positive">Sẵn sàng sử dụng</small></div><div><span>Chờ kiểm duyệt</span><strong>{pending}</strong><small>Cần xử lý</small></div><div><span>Ngừng phân phối</span><strong>{count('DEPRECATED')}</strong><small>Giữ tương thích bản cũ</small></div></section>
    <section className="admin-panel admin-theme-library"><div className="admin-library-toolbar"><label><MagnifyingGlass /><input aria-label="Tìm template" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm theo tên, mã hoặc mô tả" /></label><div role="group" aria-label="Lọc trạng thái">{([['ALL', 'Tất cả'], ['RELEASED', 'Đã xuất bản'], ['PENDING_REVIEW', 'Chờ duyệt'], ['DEPRECATED', 'Ngừng phân phối']] as const).map(([value, label]) => <button type="button" key={value} className={filter === value ? 'is-active' : ''} onClick={() => setFilter(value)}>{label} <b>{value === 'ALL' ? items.length : value === 'PENDING_REVIEW' ? pending : count(value)}</b></button>)}</div></div>
      {loading ? <div className="admin-theme-grid" aria-label="Đang tải template">{[1, 2, 3].map((key) => <article className="admin-theme-card admin-theme-skeleton" key={key}><div /><span /></article>)}</div> : error ? <Empty icon={<WarningCircle />} title="Chưa tải được kho template" text={error}><button onClick={() => void load()}><ArrowClockwise /> Thử lại</button></Empty> : visible.length ? <div className="admin-theme-grid">{visible.map((item) => { const version = item.versions[0], state = stateOf(item), previewPath = previewOf(item); return <article className="admin-theme-card" key={item.key}><div className={`admin-theme-preview ${item.key}`}><div className="admin-preview-chrome"><i /><i /><i /><span>{item.key}</span></div><div className="admin-preview-canvas"><small>THE WEDDING OF</small><strong>{item.name}</strong><i /><span>{item.description ?? 'Chưa có mô tả'}</span></div><span className={`admin-status ${state.toLowerCase()}`}>{labels[state]}</span></div><div className="admin-theme-card-body"><header><div><h2>{item.name}</h2><code>{item.key}</code></div><span>{version ? `v${version.version}` : 'Chưa có version'}</span></header><p>{item.description ?? 'Chưa cập nhật mô tả.'}</p><dl><div><dt>Đang sử dụng</dt><dd>{item.versions.reduce((total, entry) => total + entry.usageCount, 0)}</dd></div><div><dt>Cập nhật</dt><dd>{dateLabel(version?.createdAt)}</dd></div></dl></div><footer>{previewPath ? <button type="button" onClick={() => setPreview(item)}><Eye /> Xem trước</button> : <button disabled><Eye /> Thiếu previewPath</button>}<button type="button" onClick={() => { setDialogError(''); setSelected(item) }}><GearSix /> Quản lý</button></footer></article> })}</div> : <Empty icon={<Browser />} title={items.length ? 'Không tìm thấy template' : 'Chưa có template'} text={items.length ? 'Thử thay đổi từ khóa hoặc bộ lọc.' : 'Đồng bộ release bundle để bắt đầu.'}><button onClick={() => void sync()} disabled={working === 'sync'}><FileArrowUp /> Kiểm tra và đồng bộ</button></Empty>}
    </section>
    {selected ? <ManageDialog item={selected} working={working} error={dialogError} close={() => setSelected(null)} lifecycle={lifecycle} /> : null}
    {preview && previewOf(preview) ? <Dialog close={() => setPreview(null)} title={`Xem trước ${preview.name}`} subtitle="Preview được cô lập và chỉ tải khi admin chủ động mở." icon={<Eye />}><iframe className="admin-template-preview-frame" sandbox="allow-scripts allow-same-origin allow-forms" src={previewOf(preview)} title={`Preview ${preview.name}`} /></Dialog> : null}
    {syncOpen ? <Dialog close={() => !working && setSyncOpen(false)} title="Đồng bộ release bundle" subtitle="Bundle từ pipeline code/config sẽ tạo version chờ duyệt." icon={<FileArrowUp />}><label className="admin-template-bundle"><span>Release bundle JSON</span><textarea autoFocus rows={14} value={bundle} onChange={(e) => setBundle(e.target.value)} /></label>{dialogError ? <p className="admin-template-dialog-error" role="alert">{dialogError}</p> : null}<footer><button className="button button-secondary" onClick={() => setSyncOpen(false)}>Hủy</button><button className="button button-primary" disabled={!bundle.trim() || working === 'sync'} onClick={() => void sync()}>{working === 'sync' ? 'Đang đồng bộ…' : 'Kiểm tra và đồng bộ'}</button></footer></Dialog> : null}
    {notice ? <div className="admin-template-notice" role="status"><CheckCircle weight="fill" /><span>{notice}</span><button aria-label="Đóng thông báo" onClick={() => setNotice('')}><X /></button></div> : null}
  </div>
}

function Empty({ icon, title, text, children }: { icon: React.ReactNode; title: string; text: string; children: React.ReactNode }) { return <div className="admin-library-empty">{icon}<h2>{title}</h2><p>{text}</p>{children}</div> }
function Dialog({ close, title, subtitle, icon, children }: { close: () => void; title: string; subtitle: string; icon: React.ReactNode; children: React.ReactNode }) {
  const dialogRef = useRef<HTMLElement>(null), returnFocus = useRef<HTMLElement | null>(document.activeElement as HTMLElement | null)
  useEffect(() => { const dialog = dialogRef.current, focusTarget = returnFocus.current; dialog?.querySelector<HTMLElement>('button,textarea,input,[tabindex]:not([tabindex="-1"])')?.focus(); const trap = (event: KeyboardEvent) => { if (event.key !== 'Tab' || !dialog) return; const nodes = Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),textarea:not(:disabled),input:not(:disabled),[tabindex]:not([tabindex="-1"])')); if (!nodes.length) return; const first = nodes[0], last = nodes[nodes.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus() } }; document.addEventListener('keydown', trap); return () => { document.removeEventListener('keydown', trap); focusTarget?.focus() } }, [])
  return <div className="admin-template-dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) close() }}><section ref={dialogRef} className="admin-template-dialog" role="dialog" aria-modal="true" aria-label={title}><header><div>{icon}<span><h2>{title}</h2><p>{subtitle}</p></span></div><button aria-label="Đóng" onClick={close}><X /></button></header>{children}</section></div>
}
function ManageDialog({ item, working, error, close, lifecycle }: { item: AdminTemplate; working: string; error: string; close: () => void; lifecycle: (item: AdminTemplate, version: AdminTemplateVersion, action: 'release' | 'deprecate') => Promise<void> }) {
  return <Dialog close={close} title={item.name} subtitle={`${item.key} · ${item.productType}`} icon={<Code />}><div className="admin-template-version-list">{item.versions.map((version) => <VersionCard key={version.id} item={item} version={version} working={working} lifecycle={lifecycle} />)}</div>{error ? <p className="admin-template-dialog-error" role="alert">{error}</p> : null}</Dialog>
}
function VersionCard({ item, version, working, lifecycle }: { item: AdminTemplate; version: AdminTemplateVersion; working: string; lifecycle: (item: AdminTemplate, version: AdminTemplateVersion, action: 'release' | 'deprecate') => Promise<void> }) {
  const compatibility = compatibilityOf(version), auditEntries = version.recentAudit ?? []
  return <article><header><div><strong>v{version.version}</strong><span className={`admin-status ${version.reviewStatus.toLowerCase()}`}>{labels[version.reviewStatus]}</span></div><small>Config {version.templateConfigVersion} · Content {version.contentSchemaVersion} · Renderer {version.rendererApiVersion}</small></header><div className={`admin-template-compatibility ${compatibility.compatible ? 'is-compatible' : 'is-incompatible'}`}><strong>{compatibility.compatible ? 'Tương thích để phát hành' : 'Chưa tương thích'}</strong>{compatibility.issues.map((issue) => <span key={issue}>{issue}</span>)}</div><dl><div><dt>Đám cưới đang dùng</dt><dd>{version.usageCount ?? 0}</dd></div><div><dt>Source revision</dt><dd>{version.codeRevision ?? '—'}</dd></div><div><dt>Config hash</dt><dd>{version.configHash.slice(0, 12)}…</dd></div></dl><details><summary>Xem config</summary><pre>{JSON.stringify(version.config, null, 2)}</pre></details><details><summary>Lịch sử thao tác ({auditEntries.length})</summary><ol className="admin-template-audit">{auditEntries.length ? auditEntries.map((audit) => <li key={audit.id}><strong>{audit.action}</strong><span>{audit.actorUser?.displayName ?? audit.actorUser?.email ?? 'Hệ thống'} · {dateLabel(audit.occurredAt)}</span></li>) : <li>Chưa có thao tác được ghi nhận.</li>}</ol></details><footer>{version.reviewStatus === 'PENDING_REVIEW' ? <button className="button button-primary" disabled={Boolean(working) || !compatibility.compatible} onClick={() => void lifecycle(item, version, 'release')}>Phát hành version</button> : version.reviewStatus === 'RELEASED' ? <button className="button button-secondary" disabled={Boolean(working)} onClick={() => void lifecycle(item, version, 'deprecate')}>Ngừng phân phối</button> : <span>Được giữ để tương thích thiệp cũ.</span>}</footer></article>
}
