import { MagnifyingGlass, PencilSimple, Plus, Tag, Trash, X } from '@phosphor-icons/react'
import { useEffect, useMemo, useState } from 'react'
import { notifications } from '../../../shared/ui/notifications/notifications'
import { adminTemplateStylesApi, type TemplateStyle } from '../../../shared/api/admin-template-styles'

type Draft = { key: string; name: string; description: string; sortOrder: number }
const emptyDraft: Draft = { key: '', name: '', description: '', sortOrder: 0 }

export function AdminStylesPage() {
  const [styles, setStyles] = useState<TemplateStyle[]>([])
  const [query, setQuery] = useState(''), [loading, setLoading] = useState(true), [error, setError] = useState('')
  const [draft, setDraft] = useState<Draft>(emptyDraft), [editing, setEditing] = useState<TemplateStyle | null>(null), [saving, setSaving] = useState(false)
  const [showForm, setShowForm] = useState(false)

  const load = async () => { setLoading(true); setError(''); try { const result = await adminTemplateStylesApi.list(); setStyles(result.items) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải danh mục phong cách.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const visible = useMemo(() => { const value = query.trim().toLocaleLowerCase('vi'); return styles.filter((style) => !value || `${style.name} ${style.key}`.toLocaleLowerCase('vi').includes(value)) }, [query, styles])
  const openCreate = () => { setEditing(null); setDraft(emptyDraft); setShowForm(true) }
  const openEdit = (style: TemplateStyle) => { setEditing(style); setDraft({ key: style.key, name: style.name, description: style.description ?? '', sortOrder: style.sortOrder }); setShowForm(true) }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { if (editing) await adminTemplateStylesApi.update(editing.id, { ...draft, description: draft.description || null }); else await adminTemplateStylesApi.create({ ...draft, description: draft.description || null }); setShowForm(false); await load(); await notifications.success(editing ? 'Đã cập nhật danh mục' : 'Đã tạo danh mục') } catch (cause) { await notifications.error('Không thể lưu danh mục', cause instanceof Error ? cause.message : 'Vui lòng thử lại.') } finally { setSaving(false) } }
  const archive = async (style: TemplateStyle) => { const result = await notifications.confirm({ icon: 'warning', title: `Lưu trữ “${style.name}”?`, text: `${style.templateCount} template đang sử dụng danh mục này.`, confirmButtonText: 'Lưu trữ' }); if (!result.isConfirmed) return; try { await adminTemplateStylesApi.archive(style.id); await load(); await notifications.success('Đã lưu trữ danh mục') } catch (cause) { await notifications.error('Không thể lưu trữ danh mục', cause instanceof Error ? cause.message : 'Vui lòng thử lại.') } }
  return <div className="admin-dashboard admin-styles-page">
    <header className="admin-page-heading"><div><p>Nội dung & giao diện <span>/</span> Danh mục phong cách</p><h1>Danh mục phong cách</h1><span>Quản lý taxonomy dùng chung cho thiệp, website cưới và Wedding Recap.</span></div><button className="button button-primary" type="button" onClick={openCreate}><Plus /> Tạo danh mục</button></header>
    <div className="admin-styles-layout">
      <section className="admin-panel admin-style-list"><header className="admin-styles-toolbar"><label><MagnifyingGlass /><input aria-label="Tìm danh mục phong cách" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm theo tên hoặc mã" /></label><span>{styles.length} danh mục</span></header>{loading ? <div className="admin-style-skeleton" /> : error ? <div className="admin-library-empty"><Tag size={30} /><h2>Chưa tải được dữ liệu</h2><p>{error}</p><button className="button button-secondary" onClick={() => void load()}>Thử lại</button></div> : visible.length ? <div className="admin-style-rows">{visible.map((style) => <article className={`admin-style-row ${style.status === 'ARCHIVED' ? 'is-archived' : ''}`} key={style.id}><span className="admin-style-mark"><Tag size={17} /></span><div><strong>{style.name}</strong><code>{style.key}</code>{style.description ? <p>{style.description}</p> : null}</div><span className="admin-style-count">{style.templateCount} template</span><div className="admin-style-actions"><button type="button" aria-label={`Sửa ${style.name}`} onClick={() => openEdit(style)}><PencilSimple size={16} /></button>{style.status === 'ACTIVE' ? <button type="button" aria-label={`Lưu trữ ${style.name}`} onClick={() => void archive(style)}><Trash size={16} /></button> : <small>Đã lưu trữ</small>}</div></article>)}</div> : <div className="admin-library-empty"><Tag size={30} /><h2>Chưa có danh mục</h2><p>Tạo danh mục đầu tiên để bắt đầu phân loại template.</p><button className="button button-primary" onClick={openCreate}><Plus /> Tạo danh mục</button></div>}</section>
    </div>
    {showForm ? <div className="admin-style-modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) setShowForm(false) }}><form className="admin-style-modal" onSubmit={submit}><header><div><p>{editing ? 'Chỉnh sửa' : 'Tạo mới'}</p><h2>{editing ? 'Cập nhật danh mục' : 'Danh mục phong cách mới'}</h2></div><button type="button" aria-label="Đóng" onClick={() => setShowForm(false)}><X /></button></header><label>Tên hiển thị<input required maxLength={120} value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="Ví dụ: Lãng mạn" /></label><label>Mã phong cách<input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" disabled={Boolean(editing)} value={draft.key} onChange={(event) => setDraft({ ...draft, key: event.target.value })} placeholder="lang-man" /><small>Chữ thường, số và dấu gạch nối.</small></label><label>Mô tả<textarea maxLength={5000} rows={3} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Mô tả ngắn để đội vận hành dễ nhận biết…" /></label><label>Thứ tự hiển thị<input type="number" min={0} max={100000} value={draft.sortOrder} onChange={(event) => setDraft({ ...draft, sortOrder: Number(event.target.value) })} /></label><footer><button className="button button-secondary" type="button" onClick={() => setShowForm(false)}>Hủy</button><button className="button button-primary" disabled={saving} type="submit">{saving ? 'Đang lưu…' : editing ? 'Lưu thay đổi' : 'Tạo danh mục'}</button></footer></form></div> : null}
  </div>
}

