import{useRef}from'react'
import{motion,useReducedMotion,useScroll,useTransform}from'motion/react'
import{ArrowDown,Heart}from'@phosphor-icons/react'
import{winterWeddingRecapFixture}from'./fixture'
import type{WinterRecapData}from'./content'
import'./winter-wedding-recap.css'
function Snow({count=34}:{count?:number}){return <div className="wwr-snow" aria-hidden="true">{Array.from({length:count},(_,i)=><i key={i} style={{'--i':i}as React.CSSProperties}/>)}</div>}
function Reveal({children,className=''}:{children:React.ReactNode;className?:string}){const reduced=useReducedMotion();return <motion.div className={className} initial={reduced?false:{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.25}} transition={{duration:.72,ease:[.16,1,.3,1]}}>{children}</motion.div>}
export function WinterWeddingRecap({data=winterWeddingRecapFixture}:{data?:WinterRecapData}){const reduced=useReducedMotion(),strip=useRef<HTMLElement>(null),{scrollYProgress}=useScroll({target:strip,offset:['start start','end end']}),x=useTransform(scrollYProgress,[0,1],['0vw',reduced?'0vw':'-56vw']);return <main className="winter-wedding-recap">
<section className="wwr-opening" data-editor-section="opening"><motion.img src={data.chapters[0].image} alt="" initial={reduced?false:{scale:1.08}} animate={{scale:1}} transition={{duration:2.4,ease:[.16,1,.3,1]}}/><div className="wwr-opening-shade"/><div className="wwr-aurora"/><Snow/><motion.div className="wwr-opening-copy" initial={reduced?false:{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.45,duration:1}}><span>A winter love story</span><h1>{data.couple}</h1><p>{data.opening}</p><small>{data.date}<i/>{data.place}</small><a href="#winter-chapters" aria-label="Xem câu chuyện"><ArrowDown/></a></motion.div></section>
<section id="winter-chapters" className="wwr-prologue" data-editor-section="chapters"><Reveal><span>Chương một</span><h2>Lạnh trong không gian.<br/><em>Ấm trong từng khoảnh khắc.</em></h2><p>Ngày cưới trôi qua như một thước phim, bắt đầu thật khẽ và sáng dần lên trong ánh mắt của những người thân yêu.</p></Reveal></section>
<section ref={strip} className="wwr-filmstrip" data-editor-section="filmstrip"><div className="wwr-filmstrip-sticky"><motion.div className="wwr-filmstrip-track" style={{x}}>{data.chapters.map((chapter,index)=><article key={chapter.title}><figure><img src={chapter.image} alt={chapter.alt}/><div className="wwr-light-leak"/></figure><div><span>{chapter.eyebrow}</span><strong>0{index+1}</strong><h2>{chapter.title}</h2><p>{chapter.body}</p></div></article>)}</motion.div><div className="wwr-film-progress" aria-hidden="true"><i/></div></div></section>
<section className="wwr-quote" data-editor-section="quote"><Snow count={14}/><Reveal><Heart weight="thin"/><blockquote>“{data.quote.text}”</blockquote><p>{data.quote.author}</p></Reveal></section>
<section className="wwr-finale" data-editor-section="finale"><img src={data.chapters[2].image} alt={data.chapters[2].alt}/><div className="wwr-finale-shade"/><Snow count={22}/><Reveal><span>To the warmth we found</span><h2>Mãi mãi bắt đầu<br/>giữa mùa đông.</h2><p>{data.thanks}</p><strong>{data.couple}</strong></Reveal></section>
<a className="wwr-preview-exit" href="/studio/recap/themes">Đóng xem trước</a></main>}
