import type { TemplateConfig, TemplateSectionConfig } from '../../template-config'
import { sunlitSilkFixture } from './fixture'

const text = (label: string, contentKey: string, required = false) => ({
  type: 'string' as const,
  label,
  contentKey,
  ...(required ? { required: true } : {}),
})
const longText = (label: string, contentKey: string, maxLength = 300) => ({
  type: 'text' as const,
  label,
  contentKey,
  maxLength,
})
const image = (label: string, contentKey: string, mediaRole: string) => ({
  type: 'image' as const,
  label,
  contentKey,
  mediaRole,
  mediaValue: 'object' as const,
})
type SunlitSectionConfig = Exclude<TemplateSectionConfig, string>

const sections: SunlitSectionConfig[] = [
  {
    sectionKey: 'opening',
    label: 'Mở thiệp',
    required: true,
    canToggle: false,
    canReorder: false,
    fields: {
      title: text('Tên thiệp', 'opening.title', true),
      message: longText('Lời nhắn mở thiệp', 'opening.message', 180),
    },
  },
  {
    sectionKey: 'cover',
    label: 'Bìa thiệp',
    required: true,
    canToggle: false,
    canReorder: false,
    fields: {
      brideName: text('Tên cô dâu', 'couple.brideName', true),
      brideMedia: image('Ảnh cô dâu', 'couple.brideMedia', 'cover-bride'),
      groomName: text('Tên chú rể', 'couple.groomName', true),
      groomMedia: image('Ảnh chú rể', 'couple.groomMedia', 'cover-groom'),
      weddingDate: text('Ngày cưới', 'event.weddingDate', true),
      eyebrow: text('Dòng giới thiệu', 'cover.eyebrow'),
      phraseFrom: text('Dòng chữ trước hiệu ứng', 'cover.phraseFrom'),
      phraseTo: text('Dòng chữ sau hiệu ứng', 'cover.phraseTo'),
      message: longText('Lời nhắn trên bìa', 'cover.message', 180),
    },
  },
  {
    sectionKey: 'invitation',
    label: 'Lời báo hỷ',
    required: true,
    canToggle: false,
    canReorder: false,
    fields: {
      message: longText('Nội dung lời mời', 'invitation.message', 400),
    },
  },
  {
    sectionKey: 'families',
    label: 'Hai bên gia đình',
    required: true,
    canToggle: false,
    canReorder: false,
    fields: {
      title: text('Tiêu đề', 'families.title'),
      note: longText('Dòng dẫn ngày cưới', 'families.note', 180),
      brideFatherTitle: text('Danh xưng bố cô dâu', 'families.brideSide.fatherTitle'),
      brideFather: text('Tên bố cô dâu', 'families.brideSide.father'),
      brideMotherTitle: text('Danh xưng mẹ cô dâu', 'families.brideSide.motherTitle'),
      brideMother: text('Tên mẹ cô dâu', 'families.brideSide.mother'),
      brideAddress: text('Địa chỉ nhà gái', 'families.brideSide.address'),
      groomFatherTitle: text('Danh xưng bố chú rể', 'families.groomSide.fatherTitle'),
      groomFather: text('Tên bố chú rể', 'families.groomSide.father'),
      groomMotherTitle: text('Danh xưng mẹ chú rể', 'families.groomSide.motherTitle'),
      groomMother: text('Tên mẹ chú rể', 'families.groomSide.mother'),
      groomAddress: text('Địa chỉ nhà trai', 'families.groomSide.address'),
    },
  },
  {
    sectionKey: 'eventDetails',
    label: 'Hoạt động trong tiệc',
    required: true,
    canToggle: false,
    canReorder: false,
    fields: {
      title: text('Tiêu đề hoạt động', 'eventDetails.title'),
      items: {
        type: 'items' as const,
        label: 'Các hoạt động khách có thể tham gia',
        contentKey: 'eventDetails.items',
        recommendedMinItems: 3,
        maxItems: 6,
        itemFields: {
          title: { type: 'string' as const, label: 'Tên hoạt động', required: true },
          image: image('Ảnh hoạt động', 'image', 'event-activity'),
        },
      },
    },
  },
  {
    sectionKey: 'countdown',
    label: 'Đếm ngược',
    canToggle: true,
    canReorder: true,
    emptyMessage: 'Đếm ngược tự lấy ngày giờ từ thông tin sự kiện.',
    fields: {},
  },
  {
    sectionKey: 'timeline',
    label: 'Lịch trình',
    canToggle: true,
    canReorder: true,
    fields: {
      title: text('Tiêu đề lịch trình', 'timeline.title'),
      message: longText('Mô tả lịch trình', 'timeline.message', 240),
      items: {
        type: 'items' as const,
        label: 'Các mốc thời gian',
        contentKey: 'timeline.items',
        recommendedMinItems: 3,
        maxItems: 8,
        itemFields: {
          time: { type: 'time' as const, label: 'Thời gian', required: true },
          title: { type: 'string' as const, label: 'Tên hoạt động', required: true },
          description: { type: 'text' as const, label: 'Mô tả', maxLength: 200 },
        },
      },
    },
  },
  {
    sectionKey: 'venue',
    label: 'Địa điểm và bản đồ',
    canToggle: true,
    canReorder: true,
    fields: {
      title: text('Dòng giới thiệu', 'venue.title'),
      name: text('Tên địa điểm', 'venue.name', true),
      address: text('Địa chỉ', 'venue.address', true),
      message: longText('Mô tả địa điểm', 'venue.message', 240),
      mapUrl: { type: 'url' as const, label: 'Đường dẫn bản đồ', contentKey: 'venue.mapUrl' },
    },
  },
  {
    sectionKey: 'gallery',
    label: 'Album ảnh',
    canToggle: true,
    canReorder: true,
    fields: {
      kicker: text('Dòng dẫn album', 'gallery.kicker'),
      title: text('Tiêu đề album', 'gallery.title'),
      message: longText('Mô tả album', 'gallery.message', 240),
      images: {
        type: 'images' as const,
        label: 'Ảnh trong album',
        contentKey: 'galleryImages',
        mediaRole: 'gallery',
        mediaValue: 'object' as const,
        maxItems: 8,
      },
    },
  },
  {
    sectionKey: 'rsvp',
    label: 'Xác nhận tham dự',
    canToggle: true,
    canReorder: true,
    fields: {
      kicker: text('Dòng dẫn RSVP', 'rsvp.kicker'),
      title: text('Tiêu đề RSVP', 'rsvp.title'),
      message: longText('Lời nhắn RSVP', 'rsvp.message', 240),
      successMessage: longText('Lời cảm ơn sau phản hồi', 'rsvp.successMessage', 240),
    },
  },
  {
    sectionKey: 'guestbook',
    label: 'Gửi lời chúc',
    canToggle: true,
    canReorder: true,
    fields: {
      title: text('Tiêu đề sổ lưu bút', 'guestbook.title'),
      message: longText('Lời nhắn', 'guestbook.message', 240),
      successMessage: longText('Lời cảm ơn sau lời chúc', 'guestbook.successMessage', 240),
    },
  },
  {
    sectionKey: 'gift',
    label: 'Gửi tiền mừng',
    canToggle: true,
    canReorder: true,
    fields: {
      title: text('Tiêu đề', 'gift.title'),
      message: longText('Lời nhắn', 'gift.message', 240),
      thankYouMessage: longText('Lời cảm ơn', 'gift.thankYouMessage', 240),
      qrMedia: {
        type: 'image' as const,
        label: 'Mã QR mừng cưới',
        contentKey: 'giftQrMedia',
        mediaRole: 'gift-qr',
        mediaValue: 'object' as const,
      },
    },
  },
  {
    sectionKey: 'music',
    label: 'Nhạc nền',
    canToggle: true,
    canReorder: false,
    fields: {
      backgroundMusicUrl: {
        type: 'audio' as const,
        label: 'Nhạc nền',
        contentKey: 'music.backgroundMusicUrl',
        audioNameKey: 'music.backgroundMusicName',
      },
      backgroundMusicAutoplay: {
        type: 'boolean' as const,
        label: 'Tự động phát sau khi mở thiệp',
        contentKey: 'music.backgroundMusicAutoplay',
        default: false,
      },
    },
  },
  {
    sectionKey: 'footer',
    label: 'Lời cảm ơn',
    required: true,
    canToggle: false,
    canReorder: false,
    fields: {
      title: text('Tiêu đề cuối thiệp', 'footer.title'),
      message: longText('Lời cảm ơn', 'footer.message', 300),
      image: image('Ảnh cuối thiệp', 'footer.image', 'footer'),
    },
  },
]

export const sunlitSilkTemplateConfig = {
  templateKey: 'sunlit-silk',
  displayName: 'Sunlit Silk',
  templateVersion: '0.3.0',
  templateConfigVersion: '1.0',
  contentSchemaVersion: '1.0',
  rendererApiVersion: '1.0',
  status: 'ready',
  productType: 'ONLINE_INVITATION',
  type: 'invitation',
  previewPath: '/templates/invitations/sunlit-silk/preview',
  defaultData: sunlitSilkFixture,
  quickEdit: [
    { contentKey: 'couple.brideName', label: 'Tên cô dâu' },
    { contentKey: 'couple.groomName', label: 'Tên chú rể' },
    { contentKey: 'event.weddingDate', label: 'Ngày cưới' },
  ],
  capabilities: {
    commonRsvp: true,
    guestbook: true,
    gallery: true,
    calendar: true,
    maps: true,
    gift: true,
    backgroundMusic: true,
    reducedMotion: true,
  },
  palettes: [{ key: 'sunlit-silk', label: 'Sunlit Silk', default: true }],
  sections,
  composition: {
    defaultLayout: 'sunlit-silk-paper-scroll',
    layouts: {
      opening: 'envelope-reveal',
      cover: 'layered-paper-theatre',
      invitation: 'seal-and-ribbon',
      families: 'dual-cards',
      eventDetails: 'activity-carousel',
      countdown: 'floating-counters',
      timeline: 'vertical-timeline',
      venue: 'venue-card-over-map',
      gallery: 'linen-stack',
      rsvp: 'reply-card',
      guestbook: 'stacked-notes',
      gift: 'single-qr-card',
      music: 'music-dock',
      footer: 'closing-letter',
    },
    mobileFallback: 'native-vertical-scroll',
  },
  theme: {
    identity: ['sunlit-silk', 'raw-linen', 'antique-brass', 'quiet-editorial'],
    artworkManifest: 'ASSET-MANIFEST.md',
  },
} as const satisfies TemplateConfig
