import type { AuthenticatedUserActor } from '@/platform/auth/actor-context'
import { GuestError } from '../domain/guest-error'
import type { CreateCategoryData, CreateGuestData, CreateGroupData, CreateInvitationData, GuestRepository, UpdateGuestData, UpdateCategoryData, GuestImportIssue, GuestImportRow } from './ports'

export class GuestService {
  constructor(private readonly repository: GuestRepository) {}
  async list(actor: AuthenticatedUserActor, weddingId: string, filter: { query?: string | undefined; categoryId?: string | undefined; groupId?: string | undefined; limit: number; cursor?: string | undefined }) { return this.require(await this.repository.listOwned(actor.userId, weddingId, filter)) }
  async get(actor: AuthenticatedUserActor, weddingId: string, guestId: string) { return this.requireGuest(await this.repository.findOwned(actor.userId, weddingId, guestId)) }
  create(actor: AuthenticatedUserActor, weddingId: string, data: CreateGuestData) { return this.require(this.repository.createOwned(actor.userId, weddingId, data)) }
  update(actor: AuthenticatedUserActor, weddingId: string, guestId: string, data: UpdateGuestData) { return this.requireGuest(this.repository.updateOwned(actor.userId, weddingId, guestId, data)) }
  async remove(actor: AuthenticatedUserActor, weddingId: string, guestId: string) { const result = await this.repository.deleteOwned(actor.userId, weddingId, guestId); if (result === null) throw new GuestError('WEDDING_NOT_FOUND', 404, 'Wedding not found'); if (!result) throw new GuestError('GUEST_NOT_FOUND', 404, 'Guest not found') }
  categories(actor: AuthenticatedUserActor, weddingId: string) { return this.require(this.repository.listCategories(actor.userId, weddingId)) }
  createCategory(actor: AuthenticatedUserActor, weddingId: string, data: CreateCategoryData) { return this.require(this.repository.createCategory(actor.userId, weddingId, data)) }
  updateCategory(actor: AuthenticatedUserActor, weddingId: string, id: string, data: UpdateCategoryData) { return this.require(this.repository.updateCategory(actor.userId, weddingId, id, data)) }
  async removeCategory(actor: AuthenticatedUserActor, weddingId: string, id: string) { const result = await this.repository.deleteCategory(actor.userId, weddingId, id); if (result === null) throw new GuestError('WEDDING_NOT_FOUND', 404, 'Wedding not found'); if (!result) throw new GuestError('GUEST_CATEGORY_NOT_FOUND', 404, 'Guest category not found') }
  groups(actor: AuthenticatedUserActor, weddingId: string) { return this.require(this.repository.listGroups(actor.userId, weddingId)) }
  createGroup(actor: AuthenticatedUserActor, weddingId: string, data: CreateGroupData) { return this.require(this.repository.createGroup(actor.userId, weddingId, data)) }
  async removeGroup(actor: AuthenticatedUserActor, weddingId: string, id: string) { const result = await this.repository.deleteGroup(actor.userId, weddingId, id); if (result === null) throw new GuestError('WEDDING_NOT_FOUND', 404, 'Wedding not found'); if (!result) throw new GuestError('GUEST_GROUP_NOT_FOUND', 404, 'Guest group not found') }
  createInvitation(actor: AuthenticatedUserActor, weddingId: string, data: CreateInvitationData) { return this.require(this.repository.createInvitation(actor.userId, weddingId, data)) }
  rotateInvitation(actor: AuthenticatedUserActor, weddingId: string, id: string) { return this.require(this.repository.rotateInvitation(actor.userId, weddingId, id)) }
  async revokeInvitation(actor: AuthenticatedUserActor, weddingId: string, id: string) { const result = await this.repository.revokeInvitation(actor.userId, weddingId, id); if (result === null) throw new GuestError('WEDDING_NOT_FOUND', 404, 'Wedding not found'); if (!result) throw new GuestError('INVITATION_NOT_FOUND', 404, 'Invitation not found') }
  resolvePublicInvitation(weddingSlug: string, guestSlug: string) { return this.repository.resolvePublicInvitation(weddingSlug, guestSlug) }
  async exportCsv(actor: AuthenticatedUserActor, weddingId: string) { const rows = this.require(await this.repository.exportOwned(actor.userId, weddingId)); const esc = (value: string | number | null) => { const text = value === null ? '' : String(value); return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text }; const lines: Array<Array<string | number | null>> = [['Loại dòng', 'Danh mục', 'Nhóm khách', 'Tên khách mời', 'Số người dự kiến', 'Điện thoại', 'Email', 'Bàn', 'Ghi chú', 'Tags']]; let section = ''; for (const row of rows.sort((a, b) => `${a.categoryPath}\u0000${a.groupName ?? ''}\u0000${a.displayName}`.localeCompare(`${b.categoryPath}\u0000${b.groupName ?? ''}\u0000${b.displayName}`, 'vi'))) { const key = `${row.categoryPath} / ${row.groupName ?? 'Chưa phân nhóm'}`; if (key !== section) { lines.push(['NHÓM', row.categoryPath || 'Chưa phân danh mục', row.groupName ?? 'Chưa phân nhóm', '', '', '', '', '', '', '']); section = key } lines.push(['KHÁCH', row.categoryPath, row.groupName, row.displayName, row.maxPartySize, row.phone, row.email, row.tableName, row.note, row.tags.join(', ')]) } return '\uFEFF' + lines.map((line) => line.map((value) => esc(value)).join(',')).join('\r\n') + '\r\n' }
  previewImport(rows: GuestImportRow[]): { validRows: GuestImportRow[]; issues: GuestImportIssue[] } { const issues: GuestImportIssue[] = []; const validRows: GuestImportRow[] = []; rows.forEach((row, index) => { const rowNumber = index + 2; if (!row.displayName?.trim()) issues.push({ row: rowNumber, field: 'displayName', message: 'Tên khách mời là bắt buộc' }); const depth = row.categoryPath?.split('/').map((part) => part.trim()).filter(Boolean).length ?? 0; if (depth > 3) issues.push({ row: rowNumber, field: 'categoryPath', message: 'Danh mục tối đa 3 cấp' }); if (row.maxPartySize !== undefined && (!Number.isInteger(row.maxPartySize) || row.maxPartySize < 1 || row.maxPartySize > 50)) issues.push({ row: rowNumber, field: 'maxPartySize', message: 'Số người dự kiến phải từ 1 đến 50' }); if (!issues.some((issue) => issue.row === rowNumber)) validRows.push({ ...row, displayName: row.displayName.trim() }) }); return { validRows, issues } }
  async importRows(actor: AuthenticatedUserActor, weddingId: string, rows: GuestImportRow[]) { const preview = this.previewImport(rows); if (preview.issues.length) throw new GuestError('GUEST_IMPORT_VALIDATION_FAILED', 400, 'Guest import contains invalid rows'); return this.require(await this.repository.importOwned(actor.userId, weddingId, preview.validRows)) }
  private require<T>(value: T | null): T { if (value === null) throw new GuestError('WEDDING_NOT_FOUND', 404, 'Wedding not found'); return value }
  private requireGuest<T>(value: T | null): T { if (value === null) throw new GuestError('GUEST_NOT_FOUND', 404, 'Guest not found'); return value }
}
