import { useEffect, useState } from 'react'
import { Archive, CalendarBlank, FloppyDisk, Globe, Trash } from '@phosphor-icons/react'
import { useWeddingWorkspace } from '../../../entities/wedding/model/wedding-context'
import { weddingApi, WeddingApiError, type WeddingVisibility } from '../../../shared/api/weddings'
import { ConfirmDialog } from '../../../shared/ui/confirm-dialog/ConfirmDialog'

export function WeddingSettingsPage() {
  const { activeWedding, replaceWedding, removeWedding } = useWeddingWorkspace()
  const [name, setName] = useState(''), [date, setDate] = useState(''), [timezone, setTimezone] = useState('Asia/Ho_Chi_Minh')
  const [visibility, setVisibility] = useState<WeddingVisibility>('PUBLIC'), [saving, setSaving] = useState(false), [message, setMessage] = useState<string | null>(null), [deleteOpen, setDeleteOpen] = useState(false), [deleting, setDeleting] = useState(false)
  useEffect(() => { if (!activeWedding) return; setName(activeWedding.name); setDate(activeWedding.primaryDate?.slice(0, 10) ?? ''); setTimezone(activeWedding.timezone); setVisibility(activeWedding.visibility) }, [activeWedding])
  if (!activeWedding) return null
  const wedding = activeWedding
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(null); try { const result = await weddingApi.update(wedding.id, { name: name.trim(), primaryDate: date ? new Date(`${date}T12:00:00+07:00`).toISOString() : null, timezone, visibility, revision: wedding.revision }); replaceWedding(result.wedding); setMessage('Đã lưu thay đổi.') } catch (cause) { setMessage(cause instanceof WeddingApiError && cause.status === 409 ? 'Dữ liệu vừa thay đổi ở nơi khác. Hãy tải lại trước khi lưu.' : cause instanceof Error ? cause.message : 'Không thể lưu thay đổi.') } finally { setSaving(false) } }
  async function toggleArchive() { const result = await weddingApi.update(wedding.id, { status: wedding.status === 'ARCHIVED' ? 'DRAFT' : 'ARCHIVED', revision: wedding.revision }); replaceWedding(result.wedding) }
  async function destroy() { setDeleting(true); try { await weddingApi.remove(wedding.id); removeWedding(wedding.id); setDeleteOpen(false) } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Không thể xóa đám cưới.') } finally { setDeleting(false) } }
  return <div className="wedding-page settings-page"><header className="workspace-page-heading"><div><p className="eyebrow">Không gian cưới</p><h1>Cài đặt chung</h1><p>Cập nhật thông tin được dùng xuyên suốt dashboard, thiệp và các sự kiện.</p></div></header><form className="settings-layout" onSubmit={save}><section className="settings-panel"><header><CalendarBlank size={20} /><div><h2>Thông tin cơ bản</h2><p>Tên, ngày cưới và múi giờ mặc định.</p></div></header><div className="settings-fields"><label>Tên đám cưới<input required maxLength={160} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Ngày cưới chính<input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><label>Múi giờ<select value={timezone} onChange={(e) => setTimezone(e.target.value)}><option value="Asia/Ho_Chi_Minh">Việt Nam (GMT+7)</option><option value="Asia/Bangkok">Bangkok (GMT+7)</option><option value="Asia/Singapore">Singapore (GMT+8)</option></select></label></div></section><section className="settings-panel"><header><Globe size={20} /><div><h2>Quyền riêng tư mặc định</h2><p>Áp dụng cho hồ sơ cưới; publish vẫn là một bước riêng.</p></div></header><div className="visibility-options">{([['PUBLIC','Công khai'],['PASSWORD_PROTECTED','Có mật khẩu'],['INVITE_ONLY','Chỉ người được mời']] as const).map(([value,label]) => <label key={value}><input type="radio" name="visibility" checked={visibility === value} onChange={() => setVisibility(value)} /><span><strong>{label}</strong><small>{value === 'PUBLIC' ? 'Phù hợp khi chia sẻ website cưới.' : value === 'PASSWORD_PROTECTED' ? 'Khách cần mật khẩu để truy cập.' : 'Chỉ dùng qua lời mời cá nhân.'}</small></span></label>)}</div></section>{message ? <p className="workspace-save-message" role="status">{message}</p> : null}<div className="settings-save"><button className="button button-primary" disabled={saving}><FloppyDisk size={17} /> {saving ? 'Đang lưu…' : 'Lưu thay đổi'}</button></div></form><section className="danger-zone"><div><h2>Trạng thái & xóa dữ liệu</h2><p>Lưu trữ có thể mở lại. Xóa là thao tác cuối cùng và không có khôi phục trong MVP.</p></div><div><button className="button button-secondary" onClick={() => void toggleArchive()}><Archive size={17} /> {activeWedding.status === 'ARCHIVED' ? 'Mở lại bản nháp' : 'Lưu trữ'}</button><button className="button button-danger" onClick={() => setDeleteOpen(true)}><Trash size={17} /> Xóa đám cưới</button></div></section><ConfirmDialog open={deleteOpen} title="Xóa đám cưới này?" description={`“${wedding.name}” sẽ bị xóa vĩnh viễn và không thể hoàn tác.`} confirmLabel="Xóa đám cưới" busy={deleting} onCancel={() => setDeleteOpen(false)} onConfirm={destroy} /></div>
}
