import type { TemplateConfig } from '../../template-config'
import { weddingWebsiteEditorFields } from '../../shared/website-editor-fields'
const keys = [
  'navigation',
  'hero',
  'announcement',
  'couple',
  'story',
  'events',
  'countdown',
  'venues',
  'gallery',
  'schedule',
  'dressCode',
  'faq',
  'rsvp',
  'guestbook',
  'footer',
] as const
export const cherryBlossomGardenTemplateConfig = {
  templateKey: 'cherry-blossom-garden',
  displayName: 'Cherry Blossom Garden Wedding',
  productType: 'WEDDING_WEBSITE',
  templateVersion: '1.0.0',
  templateConfigVersion: 1,
  contentSchemaVersion: 1,
  rendererApiVersion: 1,
  status: 'ready',
  type: 'website',
  previewPath: '/templates/websites/cherry-blossom-garden/preview',
  description: 'Khu vườn anh đào điện ảnh nhiều lớp với cánh hoa, sương và nắng xuyên tán.',
  capabilities: { commonRsvp: true, guestbook: true, backgroundMusic: false, seo: true },
  theme: {
    palettes: ['sakura-ivory'],
    heroStyles: ['garden-gateway'],
    storyStyles: ['blossom-path'],
    galleryStyles: ['floating-memories'],
    default: {
      palette: 'sakura-ivory',
      heroStyle: 'garden-gateway',
      storyStyle: 'blossom-path',
      galleryStyle: 'floating-memories',
      typographyScale: 'AIRY',
      motionLevel: 'EXPRESSIVE',
    },
  },
  sections: keys.map((sectionKey, index) => ({
    sectionKey,
    label: sectionKey,
    required: [
      'navigation',
      'hero',
      'announcement',
      'couple',
      'events',
      'venues',
      'footer',
    ].includes(sectionKey),
    canToggle: ![
      'navigation',
      'hero',
      'announcement',
      'couple',
      'events',
      'venues',
      'footer',
    ].includes(sectionKey),
    canReorder: index > 1 && index < keys.length - 1,
    fields: weddingWebsiteEditorFields[String(sectionKey)] ?? {},
  })),
} as const satisfies TemplateConfig
