export type WeddingErrorCode =
  | 'WEDDING_NOT_FOUND'
  | 'WEDDING_REVISION_CONFLICT'
  | 'WEDDING_EVENT_NOT_FOUND'
  | 'WEDDING_EVENT_REVISION_CONFLICT'
  | 'WEDDING_CONTENT_REVISION_CONFLICT'
  | 'WEDDING_TEMPLATE_NOT_FOUND'
  | 'WEDDING_TEMPLATE_INCOMPATIBLE'
  | 'WEDDING_SECTION_INVALID'
  | 'WEDDING_NOT_READY_TO_PUBLISH'
  | 'WEDDING_SLUG_TAKEN'
  | 'WEDDING_PUBLISH_REVISION_CONFLICT'
  | 'WEDDING_PUBLIC_NOT_FOUND'
  | 'WEDDING_WISH_NOT_FOUND'
  | 'WEDDING_WISH_ALREADY_LINKED'
  | 'WEDDING_WISH_OR_GUEST_NOT_FOUND'
  | 'WEDDING_WISH_GUEST_NAME_REQUIRED'
  | 'WEDDING_GUEST_CATEGORY_NOT_FOUND'
  | 'WEDDING_GUEST_GROUP_NOT_FOUND'
  | 'WEDDING_EVENT_TIME_INVALID'

export class WeddingError extends Error {
  constructor(
    public readonly code: WeddingErrorCode,
    public readonly status: number,
    message: string,
  ) {
    super(message)
    this.name = 'WeddingError'
  }
}
