import type { TemplateConfig } from '../../template-config'
export const chibiDaydreamTemplateConfig = {
  templateKey: 'chibi-daydream',
  displayName: 'Mây Hồng Có Đôi',
  templateVersion: '1.1.1',
  templateConfigVersion: '1.0',
  contentSchemaVersion: '1.0',
  rendererApiVersion: '1.0',
  status: 'review',
  productType: 'ONLINE_INVITATION',
  type: 'invitation',
  previewPath: '/templates/invitations/chibi-daydream/preview',
  quickEdit: [
    { contentKey: 'brideName', label: 'Tên cô dâu' },
    { contentKey: 'groomName', label: 'Tên chú rể' },
  ],
  palettes: [{ key: 'storybook', label: 'Mây hồng', default: true }],
  sections: [
    {
      sectionKey: 'cover',
      label: 'Popup mở thiệp',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        brideName: { type: 'string', label: 'Tên cô dâu', required: true, maxLength: 80 },
        groomName: { type: 'string', label: 'Tên chú rể', required: true, maxLength: 80 },
        weddingDate: { type: 'string', label: 'Ngày cưới', required: true, maxLength: 40 },
      },
    },
    {
      sectionKey: 'banner',
      label: 'Banner cặp đôi',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        brideName: { type: 'string', contentKey: 'brideName', label: 'Tên cô dâu' },
        groomName: { type: 'string', contentKey: 'groomName', label: 'Tên chú rể' },
        image: { type: 'image', label: 'Ảnh banner', mediaRole: 'hero' },
      },
    },
    {
      sectionKey: 'invitation',
      label: 'Lời báo hỷ',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        title: {
          type: 'string',
          contentKey: 'invitationTitle',
          label: 'Tiêu đề lời báo hỷ',
          maxLength: 160,
        },
        message: {
          type: 'text',
          contentKey: 'invitationMessage',
          label: 'Nội dung lời báo hỷ',
          maxLength: 600,
        },
      },
    },
    {
      sectionKey: 'families',
      label: 'Hai bên gia đình',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        brideFather: { type: 'string', label: 'Tên bố cô dâu' },
        brideMother: { type: 'string', label: 'Tên mẹ cô dâu' },
        groomFather: { type: 'string', label: 'Tên bố chú rể' },
        groomMother: { type: 'string', label: 'Tên mẹ chú rể' },
      },
    },
    {
      sectionKey: 'ceremony',
      label: 'Lễ thành hôn',
      required: true,
      canToggle: false,
      canReorder: true,
      fields: {
        time: { type: 'time', contentKey: 'ceremonyTime', label: 'Thời gian làm lễ' },
        date: { type: 'string', contentKey: 'weddingDate', label: 'Ngày làm lễ' },
      },
    },
    {
      sectionKey: 'reception',
      label: 'Tiệc cưới',
      required: true,
      canToggle: false,
      canReorder: true,
      fields: {
        time: { type: 'time', contentKey: 'receptionTime', label: 'Thời gian đãi tiệc' },
        venue: { type: 'string', contentKey: 'venueName', label: 'Tên địa điểm' },
        address: { type: 'string', contentKey: 'venueAddress', label: 'Địa chỉ' },
      },
    },
    {
      sectionKey: 'calendar',
      label: 'Lịch ngày cưới',
      canToggle: true,
      canReorder: true,
      fields: {},
    },
    {
      sectionKey: 'gallery',
      label: 'Album ảnh',
      canToggle: true,
      canReorder: true,
      fields: {
        images: {
          type: 'images',
          contentKey: 'galleryImages',
          label: 'Ảnh trong album',
          mediaRole: 'gallery',
          maxItems: 12,
        },
      },
    },
    {
      sectionKey: 'timeline',
      label: 'Lịch trình',
      canToggle: true,
      canReorder: true,
      fields: {
        items: {
          type: 'items',
          recommendedMinItems: 3,
          contentKey: 'timelineItems',
          label: 'Các mốc thời gian',
          maxItems: 10,
          itemFields: {
            time: { type: 'time', label: 'Thời gian' },
            title: { type: 'string', label: 'Tiêu đề' },
            detail: { type: 'text', label: 'Mô tả' },
          },
        },
      },
    },
    {
      sectionKey: 'rsvp',
      label: 'Xác nhận tham dự',
      canToggle: true,
      canReorder: true,
      fields: {
        deadline: { type: 'date', contentKey: 'rsvpDeadline', label: 'Hạn phản hồi' },
        message: { type: 'text', contentKey: 'rsvpMessage', label: 'Lời nhắn RSVP' },
      },
    },
    {
      sectionKey: 'map',
      label: 'Bản đồ',
      canToggle: true,
      canReorder: true,
      fields: {
        mapUrl: { type: 'url', contentKey: 'mapUrl', label: 'Đường dẫn bản đồ' },
        venue: { type: 'string', contentKey: 'venueName', label: 'Tên địa điểm' },
        address: { type: 'string', contentKey: 'venueAddress', label: 'Địa chỉ' },
      },
    },
    { sectionKey: 'guestbook', label: 'Sổ lưu bút', canToggle: true, canReorder: true, fields: {} },
    {
      sectionKey: 'gift',
      label: 'Quà mừng',
      canToggle: true,
      canReorder: true,
      fields: {
        message: { type: 'text', contentKey: 'giftMessage', label: 'Lời nhắn quà mừng' },
        qr: {
          type: 'image',
          contentKey: 'giftQrMedia',
          label: 'Mã QR quà mừng',
          mediaRole: 'gift-qr',
        },
      },
    },
    {
      sectionKey: 'thanks',
      label: 'Lời cảm ơn',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        message: { type: 'text', contentKey: 'thanksMessage', label: 'Lời cảm ơn', maxLength: 300 },
        media: {
          type: 'image',
          contentKey: 'thanksMedia',
          label: 'Ảnh cuối thiệp',
          mediaRole: 'footer',
        },
      },
    },
  ],
} as const satisfies TemplateConfig
