import { useEffect, useState } from 'react'
import { CalendarBlank, Clock, MapPin, PencilSimple, Plus, Trash, X } from '@phosphor-icons/react'
import { useWeddingWorkspace } from '../../../entities/wedding/model/wedding-context'
import { weddingApi, WeddingApiError, type WeddingEvent } from '../../../shared/api/weddings'
import { formatDateTime } from '../../../shared/lib/date/date-format'
import { buildEventInput } from '../model/event-input'
import { ConfirmDialog } from '../../../shared/ui/confirm-dialog/ConfirmDialog'

const blank = { name: '', eventType: 'CEREMONY', startsAt: '', endsAt: '', venueName: '', addressLine: '', mapUrl: '', isPublic: true }
export function WeddingEventsPage() {
  const { activeWedding } = useWeddingWorkspace()
  const [items, setItems] = useState<WeddingEvent[]>([]), [loading, setLoading] = useState(true), [open, setOpen] = useState(false)
  const [editing, setEditing] = useState<WeddingEvent | null>(null), [form, setForm] = useState(blank)
  const [error, setError] = useState<string | null>(null), [saving, setSaving] = useState(false), [pendingDelete, setPendingDelete] = useState<WeddingEvent | null>(null), [deleting, setDeleting] = useState(false)
  const weddingId = activeWedding?.id
  async function load() { if (!activeWedding) return; setLoading(true); try { setItems((await weddingApi.events(activeWedding.id)).items); setError(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải lịch lễ.') } finally { setLoading(false) } }
  useEffect(() => { if (!weddingId) return; setLoading(true); weddingApi.events(weddingId).then((result) => { setItems(result.items); setError(null) }).catch((cause) => setError(cause instanceof Error ? cause.message : 'Không thể tải lịch lễ.')).finally(() => setLoading(false)) }, [weddingId])
  function show(item?: WeddingEvent) { setEditing(item ?? null); setError(null); setForm(item ? { name: item.name, eventType: item.eventType, startsAt: item.startsAt.slice(0, 16), endsAt: item.endsAt?.slice(0, 16) ?? '', venueName: item.venueName ?? '', addressLine: item.addressLine ?? '', mapUrl: item.mapUrl ?? '', isPublic: item.isPublic } : blank); setOpen(true) }
  async function save(event: React.FormEvent) {
    event.preventDefault(); if (!activeWedding) return; setSaving(true); setError(null)
    let input
    try { input = buildEventInput(form, activeWedding.timezone, Boolean(editing)) }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Dữ liệu sự kiện không hợp lệ.'); setSaving(false); return }
    try { const result = editing ? await weddingApi.updateEvent(activeWedding.id, editing.id, { ...input, revision: editing.revision }) : await weddingApi.createEvent(activeWedding.id, input); setItems((current) => editing ? current.map((item) => item.id === result.event.id ? result.event : item) : [...current, result.event].sort((a, b) => a.startsAt.localeCompare(b.startsAt))); setOpen(false) }
    catch (cause) { setError(cause instanceof WeddingApiError && cause.status === 409 ? 'Sự kiện vừa được chỉnh sửa ở nơi khác. Danh sách đã được tải lại.' : cause instanceof Error ? cause.message : 'Không thể lưu sự kiện.'); if (cause instanceof WeddingApiError && cause.status === 409) void load() }
    finally { setSaving(false) }
  }
  async function remove() { if (!activeWedding || !pendingDelete) return; setDeleting(true); setError(null); try { await weddingApi.removeEvent(activeWedding.id, pendingDelete.id); setItems((current) => current.filter(({ id }) => id !== pendingDelete.id)); setPendingDelete(null) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể xóa sự kiện.') } finally { setDeleting(false) } }
  return <div className="wedding-page events-page"><header className="workspace-page-heading"><div><p className="eyebrow">Lịch cưới</p><h1>Lễ & tiệc</h1><p>Một nguồn thông tin dùng chung cho thiệp, website, bản đồ và RSVP.</p></div><button className="button button-primary" onClick={() => show()}><Plus size={17} /> Thêm sự kiện</button></header>
    {error && !open ? <div className="workspace-alert" role="alert">{error}<button onClick={() => void load()}>Thử lại</button></div> : null}
    {loading ? <div className="workspace-skeleton" aria-label="Đang tải lịch lễ" role="status"><i /><i /><i /></div> : items.length === 0 ? <section className="workspace-empty"><CalendarBlank size={34} weight="duotone" /><h2>Chưa có lễ hoặc tiệc nào</h2><p>Thêm lễ vu quy, thành hôn hoặc tiệc cưới để khách luôn nhận đúng thời gian và địa điểm.</p><button className="button button-primary" onClick={() => show()}><Plus size={17} /> Thêm sự kiện đầu tiên</button></section> : <div className="event-list">{items.map((item) => { const date = new Date(item.startsAt); return <article className="event-card" key={item.id}><time><strong>{String(date.getDate()).padStart(2, '0')}</strong><span>{String(date.getMonth() + 1).padStart(2, '0')}/{date.getFullYear()}</span></time><div className="event-card-copy"><div><span className="event-kind">{item.eventType}</span>{!item.isPublic ? <span className="private-pill">Riêng tư</span> : null}</div><h2>{item.name}</h2><p><Clock size={15} /> {formatDateTime(item.startsAt)}</p><p><MapPin size={15} /> {item.venueName || item.addressLine || 'Chưa nhập địa điểm'}</p></div><div className="event-card-actions"><button aria-label={`Sửa ${item.name}`} onClick={() => show(item)}><PencilSimple size={17} /></button><button className="danger" aria-label={`Xóa ${item.name}`} onClick={() => setPendingDelete(item)}><Trash size={17} /></button></div></article> })}</div>}
    {open ? <div className="workspace-dialog-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false) }}><form className="workspace-dialog" onSubmit={save}><header><div><p className="eyebrow">{editing ? 'Chỉnh sửa' : 'Sự kiện mới'}</p><h2>{editing ? editing.name : 'Thêm lễ hoặc tiệc'}</h2></div><button type="button" aria-label="Đóng" onClick={() => setOpen(false)}><X size={18} /></button></header><div className="workspace-form-grid"><label className="span-2">Tên sự kiện<input required maxLength={160} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Loại<select value={form.eventType} onChange={(e) => setForm({ ...form, eventType: e.target.value })}><option value="CEREMONY">Lễ thành hôn</option><option value="VU_QUY">Lễ vu quy</option><option value="RECEPTION">Tiệc cưới</option><option value="OTHER">Khác</option></select></label><label>Hiển thị<select value={String(form.isPublic)} onChange={(e) => setForm({ ...form, isPublic: e.target.value === 'true' })}><option value="true">Công khai</option><option value="false">Riêng tư</option></select></label><label>Bắt đầu<input required type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} /></label><label>Kết thúc<input type="datetime-local" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} /></label><label>Tên địa điểm<input value={form.venueName} onChange={(e) => setForm({ ...form, venueName: e.target.value })} /></label><label>Địa chỉ<input value={form.addressLine} onChange={(e) => setForm({ ...form, addressLine: e.target.value })} /></label><label className="span-2">Link bản đồ<input type="url" value={form.mapUrl} onChange={(e) => setForm({ ...form, mapUrl: e.target.value })} /></label></div>{error ? <p className="workspace-form-error" role="alert">{error}</p> : null}<footer><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="button button-primary" disabled={saving}>{saving ? 'Đang lưu…' : 'Lưu sự kiện'}</button></footer></form></div> : null}
    <ConfirmDialog open={Boolean(pendingDelete)} title="Xóa sự kiện này?" description={pendingDelete ? `“${pendingDelete.name}” sẽ bị xóa khỏi lịch cưới.` : ''} confirmLabel="Xóa sự kiện" busy={deleting} onCancel={() => setPendingDelete(null)} onConfirm={remove} />
  </div>
}
