import { ArrowRight, CheckCircle, Heart, Image, ListChecks, PaperPlaneTilt, Sparkle, UsersThree } from '@phosphor-icons/react'
import { AppLink } from '../../../shared/lib/navigation/AppLink'
import { marketingRoutes, studioRoutes } from '../../../shared/config/routes'
import { BrandLogo } from '../../../shared/ui/BrandLogo'
import './how-it-works.css'

const steps = [
  { icon: Sparkle, number: '01', title: 'Chọn một khởi đầu có gu', text: 'Bắt đầu bằng thiệp online, website cưới hoặc một trang Recap. Mỗi mẫu đã có sẵn nhịp bố cục để bạn không phải bắt đầu từ trang trắng.' },
  { icon: Image, number: '02', title: 'Kể câu chuyện riêng', text: 'Thêm tên hai bạn, ảnh, lịch trình, địa điểm và những lời nhắn muốn gửi. Mọi thay đổi đều được xem trước ngay trên cả desktop và mobile.' },
  { icon: UsersThree, number: '03', title: 'Mời mọi người cùng chuẩn bị', text: 'Quản lý khách mời, RSVP, lời chúc và phân quyền cho người thân hoặc planner cùng đồng hành trong Wedding.' },
  { icon: PaperPlaneTilt, number: '04', title: 'Chia sẻ và lưu lại', text: 'Gửi đường dẫn hoặc mã QR đến khách mời. Sau ngày vui, những hình ảnh và lời chúc vẫn ở lại trong câu chuyện của hai bạn.' },
]

export function HowItWorksPage() {
  return <div className="how-it-works-page"><header className="how-nav"><AppLink to={marketingRoutes.home} className="how-brand"><BrandLogo /></AppLink><nav><AppLink to={marketingRoutes.invitationTemplates}>Giao diện mẫu</AppLink><AppLink className="is-active" to={marketingRoutes.howItWorks}>Cách hoạt động</AppLink><AppLink to={marketingRoutes.faq}>Hỏi đáp</AppLink><AppLink to={marketingRoutes.login}>Đăng nhập</AppLink></nav><AppLink to={studioRoutes.inviteThemes} className="how-cta">Bắt đầu tạo <ArrowRight size={16} /></AppLink></header><main><section className="how-hero"><span className="public-library-eyebrow"><Heart weight="fill" /> Một hành trình liền mạch</span><h1>Từ lời mời đầu tiên đến những ký ức sau ngày cưới.</h1><p>Ourday gom những việc quan trọng vào một không gian nhẹ nhàng, để hai bạn có thể tập trung vào điều đáng nhớ nhất.</p><AppLink to={studioRoutes.inviteThemes} className="how-primary">Khám phá giao diện <ArrowRight /></AppLink></section><section className="how-steps" aria-label="Các bước sử dụng Ourday">{steps.map(({ icon: Icon, number, title, text }) => <article key={number}><span className="how-step-number">{number}</span><Icon size={28} /><h2>{title}</h2><p>{text}</p></article>)}</section><section className="how-workspace"><div><span className="public-library-eyebrow"><ListChecks /> Một không gian cho cả hai</span><h2>Đẹp ở bên ngoài, gọn gàng ở bên trong.</h2><p>Thiệp, website, khách mời, checklist và sổ tiền mừng được kết nối để việc chuẩn bị không bị rơi vào quá nhiều công cụ rời rạc.</p><AppLink to={studioRoutes.home} className="how-text-link">Vào không gian Wedding <ArrowRight /></AppLink></div><div className="how-workspace-card"><div><CheckCircle weight="fill" /><span><strong>Thiệp online</strong> Sẵn sàng chia sẻ</span></div><div><UsersThree /><span><strong>Khách mời</strong> RSVP và lời chúc</span></div><div><ListChecks /><span><strong>Todolist</strong> Theo dõi tiến độ</span></div></div></section><section className="how-final"><Sparkle size={24} /><h2>Ngày trọng đại bắt đầu từ một điều rất riêng.</h2><p>Chọn mẫu đầu tiên của hai bạn và bắt đầu viết câu chuyện.</p><AppLink to={marketingRoutes.invitationTemplates} className="how-primary">Xem giao diện mẫu <ArrowRight /></AppLink></section></main></div>
}
