import { useEffect, useMemo, useState } from 'react'
import type { CSSProperties } from 'react'
import { CaretDown, CaretRight, DotsThree, FolderSimple, Plus, TreeStructure, UsersThree, X } from '@phosphor-icons/react'
import { guestCategoryApi, type GuestCategory, type Wedding } from '../../../shared/api/weddings'
import { useOptionalWeddingWorkspace } from '../../../entities/wedding/model/wedding-context'
import { GuestCategoriesPage } from './GuestCategoriesPage'

export function GuestCategoriesConnected() {
  const workspace = useOptionalWeddingWorkspace(); if (!workspace) return <GuestCategoriesPage />
  return <GuestCategoriesConnectedContent activeWedding={workspace.activeWedding} />
}

function GuestCategoriesConnectedContent({ activeWedding }: { activeWedding: Wedding | null }) {
  const [items, setItems] = useState<GuestCategory[]>([]); const [expanded, setExpanded] = useState<Set<string>>(new Set()); const [parent, setParent] = useState<GuestCategory | null | undefined>(undefined); const [name, setName] = useState(''); const [selected, setSelected] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const load = async () => { if (!activeWedding) return; setLoading(true); try { const result = await guestCategoryApi.list(activeWedding.id); setItems(result.items); setExpanded(new Set(result.items.filter((item) => item.depth < 3).map((item) => item.id))) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tải danh mục.') } finally { setLoading(false) } }; // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load() }, [activeWedding?.id])
  const roots = useMemo(() => items.filter((item) => item.parentId === null), [items]); const children = (id: string) => items.filter((item) => item.parentId === id); const open = (value: GuestCategory | null) => { setParent(value); setName(''); setError('') }; const create = async () => { if (!activeWedding || !name.trim()) return; if ((parent?.depth ?? 0) >= 3) { setError('Danh mục chỉ được tối đa 3 cấp.'); return }; setBusy(true); try { const result = await guestCategoryApi.create(activeWedding.id, { name: name.trim(), parentId: parent?.id ?? null }); setItems((current) => [...current, result.category]); setParent(undefined) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể tạo danh mục.') } finally { setBusy(false) } }; const remove = async () => { if (!activeWedding || !selected.length || !window.confirm(`Xóa ${selected.length} danh mục đã chọn?`)) return; setBusy(true); try { await guestCategoryApi.removeMany(activeWedding.id, selected); setItems((current) => current.filter((item) => !selected.includes(item.id))); setSelected([]) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Không thể xóa danh mục.') } finally { setBusy(false) } }
  const render = (item: GuestCategory) => { const nested = children(item.id); const isOpen = expanded.has(item.id); return <li key={item.id}><div className="category-row" style={{ '--category-depth': item.depth } as CSSProperties}><button className="category-toggle" type="button" disabled={!nested.length} onClick={() => setExpanded((current) => { const next = new Set(current); if (next.has(item.id)) next.delete(item.id); else next.add(item.id); return next })} aria-label="Mở rộng danh mục">{nested.length ? isOpen ? <CaretDown size={15} /> : <CaretRight size={15} /> : <span />}</button><input className="guest-checkbox" type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} aria-label={`Chọn ${item.name}`} /><span className="category-folder"><FolderSimple size={18} weight={isOpen ? 'fill' : 'regular'} /></span><div className="category-copy"><strong>{item.name}</strong><span>Cấp {item.depth}</span></div><span className="category-count"><UsersThree size={14} /> {item.guestCount ?? 0} khách</span>{item.depth < 3 ? <button className="category-add-child" type="button" onClick={() => open(item)}> <Plus size={14} /> Thêm cấp con</button> : <span className="category-limit">Cấp cuối</span>}<button className="row-menu" type="button" aria-label={`Tùy chọn ${item.name}`}><DotsThree size={18} weight="bold" /></button></div>{nested.length && isOpen ? <ul>{nested.map(render)}</ul> : null}</li> }
  return <section className="categories-page" aria-labelledby="categories-heading"><header className="categories-heading"><div><p className="breadcrumb">Đám cưới <span>/</span> Khách mời <span>/</span> Danh mục</p><h1 id="categories-heading">Danh mục khách mời</h1><p>Tổ chức khách theo cây danh mục tối đa 3 cấp để lọc thuận tiện hơn.</p></div><button className="button button-primary" type="button" onClick={() => open(null)}><Plus size={17} /> Thêm danh mục</button></header><div className="category-summary"><div><TreeStructure size={19} /><span><strong>{items.length}</strong> danh mục</span></div><p><strong>3 cấp tối đa</strong><span>Danh mục được đồng bộ trực tiếp với danh sách khách mời.</span></p></div><div className="panel category-tree-panel"><header><div><h2>Cây danh mục</h2><p>Chọn nhiều danh mục để xóa khi nhập sai.</p></div>{selected.length ? <button className="button button-secondary" type="button" disabled={busy} onClick={() => void remove()}>Xóa {selected.length} mục</button> : <span>{roots.length} danh mục gốc</span>}</header>{loading ? <div className="guest-empty">Đang tải danh mục…</div> : error ? <div className="guest-empty"><p>{error}</p><button className="button button-secondary" type="button" onClick={() => void load()}>Thử lại</button></div> : <ul className="category-tree">{roots.map(render)}</ul>}</div>{parent !== undefined && <div className="category-dialog-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setParent(undefined) }}><section className="category-dialog" role="dialog" aria-modal="true"><header><div><h2>{parent ? 'Thêm danh mục con' : 'Thêm danh mục gốc'}</h2><p>{parent ? `Nằm trong “${parent.name}” · Cấp ${parent.depth + 1}` : 'Danh mục cấp 1'}</p></div><button type="button" onClick={() => setParent(undefined)} aria-label="Đóng"><X size={18} /></button></header><label htmlFor="category-name">Tên danh mục</label><input id="category-name" autoFocus value={name} onChange={(event) => { setName(event.target.value); setError('') }} onKeyDown={(event) => { if (event.key === 'Enter') void create() }} placeholder="Ví dụ: Họ nội, Bạn đại học" />{error && <p className="field-error">{error}</p>}<footer><button className="button button-secondary" type="button" onClick={() => setParent(undefined)}>Hủy</button><button className="button button-primary" type="button" disabled={busy || !name.trim()} onClick={() => void create()}>Tạo danh mục</button></footer></section></div>}</section>
}
