export const modernLuxeTemplateConfig = {
  templateKey: 'modern-luxe',
  displayName: 'Élan d’Amour',
  templateVersion: '1.1.0',
  templateConfigVersion: '1.0',
  contentSchemaVersion: '1.0',
  rendererApiVersion: '1.0',
  status: 'development',
  type: 'invitation',
  palettes: [
    { key: 'champagne', label: 'Champagne', default: true },
    { key: 'midnight', label: 'Midnight' },
    { key: 'sage', label: 'Sage' },
  ],
  sections: [
    { sectionKey: 'cover', label: 'Bìa thiệp', required: true, canToggle: false, canReorder: false, fields: { brideName: { type: 'string', required: true, maxLength: 80 }, groomName: { type: 'string', required: true, maxLength: 80 }, weddingDate: { type: 'date', required: true }, eyebrow: { type: 'string', maxLength: 80 } } },
    { sectionKey: 'invitation', label: 'Lời mời', required: true, canToggle: false, canReorder: false, fields: { title: { type: 'string', maxLength: 120 }, message: { type: 'text', maxLength: 500 } } },
    { sectionKey: 'families', label: 'Thông tin hai gia đình', canToggle: true, canReorder: true, fields: { brideFather: { type: 'string', maxLength: 80 }, brideMother: { type: 'string', maxLength: 80 }, groomFather: { type: 'string', maxLength: 80 }, groomMother: { type: 'string', maxLength: 80 } } },
    { sectionKey: 'eventDetails', label: 'Thời gian hôn lễ', canToggle: false, canReorder: false, fields: { ceremonyTime: { type: 'time' }, receptionTime: { type: 'time' } } },
    { sectionKey: 'countdown', label: 'Đếm ngược', canToggle: true, canReorder: true, fields: {} },
    { sectionKey: 'timeline', label: 'Lịch trình', canToggle: true, canReorder: true, fields: {} },
    { sectionKey: 'venue', label: 'Địa điểm và bản đồ', canToggle: true, canReorder: true, fields: { venueName: { type: 'string', required: true }, venueAddress: { type: 'string', required: true }, mapUrl: { type: 'url' }, calendarUrl: { type: 'url' } } },
    { sectionKey: 'gallery', label: 'Album ảnh', canToggle: true, canReorder: true, fields: { images: { type: 'images', maxItems: 12 } } },
    { sectionKey: 'rsvp', label: 'Xác nhận tham dự', canToggle: true, canReorder: true, fields: { deadline: { type: 'date' }, message: { type: 'string', maxLength: 180 } } },
    { sectionKey: 'guestbook', label: 'Sổ lưu bút', canToggle: true, canReorder: true, fields: {} },
    { sectionKey: 'gift', label: 'Thông tin mừng cưới', canToggle: true, canReorder: true, fields: { message: { type: 'text', maxLength: 300 } } },
  ],
} as const
