import { useEffect, useState } from 'react'
import { useOptionalAuth } from '../../../features/auth/model/auth-context'
import { weddingApi, type PublishedWeddingSnapshot } from '../../../shared/api/weddings'
import { PageLoading } from '../../../shared/ui/PageLoading'
import { StatusPage } from '../../status/ui/StatusPage'
import { EditorialVowsWebsite } from '../../../templates/websites/editorial-vows/EditorialVowsWebsite'
import { GreenHydrangeaWebsite } from '../../../templates/websites/green-hydrangea/GreenHydrangeaWebsite'
import { EnchantedForestWebsite } from '../../../templates/websites/enchanted-forest/EnchantedForestWebsite'
import { CherryBlossomGardenWebsite } from '../../../templates/websites/cherry-blossom-garden/CherryBlossomGardenWebsite'

export function PublicWebsitePageNext({ weddingSlug }: { weddingSlug: string }) {
  const auth = useOptionalAuth(); const [snapshot, setSnapshot] = useState<PublishedWeddingSnapshot>(); const [loading, setLoading] = useState(true); const [notFound, setNotFound] = useState(false); const [error, setError] = useState('')
  useEffect(() => { let active = true; setLoading(true); setNotFound(false); setError(''); void (async () => { try { const result = await weddingApi.publicWebsite(weddingSlug); if (active) setSnapshot(result.snapshot); return } catch { const signedIn = auth?.checkUserSession ? await auth.checkUserSession() : false; if (!signedIn) { if (active) setNotFound(true); return } try { const wedding = (await weddingApi.list()).items.find((item) => item.slug === weddingSlug); if (!wedding) throw new Error('not found'); const content = (await weddingApi.content(wedding.id, 'WEDDING_WEBSITE')).content; if (!content.templateVersion) throw new Error('not found'); if (active) setSnapshot({ id: `draft-${wedding.id}`, weddingId: wedding.id, surface: 'WEDDING_WEBSITE', slug: wedding.slug ?? weddingSlug, version: 0, publishedAt: new Date(0).toISOString(), payload: { surface: 'WEDDING_WEBSITE', template: { key: content.templateVersion.key, version: content.templateVersion.version }, content: content.content, theme: { themeConfig: content.themeConfig, sectionConfig: content.sectionConfig } }, templateVersion: { key: content.templateVersion.key, version: content.templateVersion.version } }) } catch { if (active) setNotFound(true) } } finally { if (active) setLoading(false) } })(); return () => { active = false } }, [auth?.checkUserSession, weddingSlug])
  if (notFound) return <StatusPage kind="not-found" />; if (loading || !snapshot) return <PageLoading label="Đang chuẩn bị website cưới" detail="Một chút nữa thôi, website đang được mở ra." />; if (error) return <StatusPage kind="server-error" />
  const payload = snapshot.payload as { template: { key: string }; content?: unknown; theme?: { sectionConfig?: unknown } }; const content = payload.content ?? {}; const config = payload.theme?.sectionConfig
  switch (payload.template.key) { case 'editorial-vows': return <EditorialVowsWebsite data={content as never} sectionConfig={config as never} />; case 'green-hydrangea': return <GreenHydrangeaWebsite data={content as never} sectionConfig={config as never} />; case 'enchanted-forest': return <EnchantedForestWebsite data={content as never} sectionConfig={config as never} />; case 'cherry-blossom-garden': return <CherryBlossomGardenWebsite data={content as never} sectionConfig={config as never} />; default: return <StatusPage kind="not-found" /> }
}
