import type { TemplateConfig } from '../../template-config'

const text = (label: string, contentKey?: string, extra: Record<string, unknown> = {}) => ({
  type: 'string' as const,
  label,
  ...(contentKey ? { contentKey } : {}),
  ...extra,
})
const multiline = (label: string, contentKey: string, maxLength = 600) => ({
  type: 'text' as const,
  label,
  contentKey,
  maxLength,
})
const image = (label: string, contentKey: string, mediaRole: string) => ({
  type: 'image' as const,
  label,
  contentKey,
  mediaRole,
  mediaValue: 'url' as const,
})

export const peonyVerandaTemplateConfig = {
  templateKey: 'peony-veranda',
  displayName: 'Peony Veranda',
  templateVersion: '1.0.0',
  templateConfigVersion: '1.0',
  contentSchemaVersion: '1.0',
  rendererApiVersion: '1.0',
  status: 'ready',
  productType: 'ONLINE_INVITATION',
  type: 'invitation',
  previewPath: '/templates/invitations/peony-veranda/preview',
  quickEdit: [
    { contentKey: 'brideName', label: 'Tên cô dâu' },
    { contentKey: 'groomName', label: 'Tên chú rể' },
    { contentKey: 'weddingDate', label: 'Ngày cưới' },
  ],
  palettes: [{ key: 'peony-veranda', label: 'Peony Veranda', default: true }],
  capabilities: {
    commonRsvp: true,
    guestbook: true,
    gallery: true,
    calendar: true,
    maps: true,
    gift: true,
    activities: true,
    backgroundMusic: true,
    smoothScroll: true,
    reducedMotion: true,
  },
  theme: {
    identity: ['peony-botanical', 'veranda-paper', 'rose-depth', 'floating-petals'],
    default: {
      palette: 'peony-veranda',
      motionLevel: 'EXPRESSIVE',
      galleryStyle: '3d-photo-transition',
    },
    artworkManifest: 'ASSET_MANIFEST.md',
  },
  composition: {
    defaultLayout: 'vertical-editorial-scroll',
    layouts: {
      cover: 'immersive-opening',
      couple: '3d-orbital-medallion',
      gallery: '3d-photo-stack',
      timeline: 'editorial-vertical-path',
      guestbook: 'wish-note-collage',
    },
    mobileFallback: 'native-vertical-scroll-2d',
    reducedMotionFallback: 'static-layered-composition',
  },
  motion: {
    level: 'EXPRESSIVE',
    smoothScroll: {
      desktop: 'lenis-progressive-enhancement',
      mobile: 'native-scroll',
      reducedMotion: 'native-scroll',
    },
    signature: '3d-gallery-transition-with-botanical-parallax',
    performanceBudget: { maxAnimatedNodes: 24, maxConcurrentDecor: 8, pauseWhenHidden: true },
  },
  sections: [
    {
      sectionKey: 'cover',
      label: 'Bìa thiệp',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        coverEyebrow: text('Dòng giới thiệu bìa'),
        brideName: text('Tên cô dâu', 'brideName', { required: true, maxLength: 80 }),
        groomName: text('Tên chú rể', 'groomName', { required: true, maxLength: 80 }),
        weddingDate: text('Ngày cưới', 'weddingDate', { required: true, maxLength: 40 }),
      },
    },
    {
      sectionKey: 'banner',
      label: 'Banner cặp đôi',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        eyebrow: text('Dòng mời', 'eyebrow'),
        bannerIntro: text('Lời mở đầu banner', 'bannerIntro', { maxLength: 180 }),
        bannerNote: text('Ghi chú banner', 'bannerNote', { maxLength: 240 }),
        bannerIndex: text('Số thứ tự banner', 'bannerIndex', { maxLength: 30 }),
        bannerImage: image('Ảnh banner', 'bannerImage', 'hero'),
      },
    },
    {
      sectionKey: 'announcement',
      label: 'Lời báo tin',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        announcementKicker: text('Dòng dẫn'),
        invitationTitle: text('Tiêu đề', 'invitationTitle', { maxLength: 160 }),
        invitationMessage: multiline('Nội dung', 'invitationMessage'),
        announcementSignoff: text('Dòng ký tên'),
      },
    },
    {
      sectionKey: 'families',
      label: 'Hai bên gia đình',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        familiesEyebrow: text('Dòng dẫn'),
        familiesTitle: text('Tiêu đề'),
        brideFatherName: text('Tên ba cô dâu', undefined, { maxLength: 120 }),
        brideMotherName: text('Tên mẹ cô dâu', undefined, { maxLength: 120 }),
        brideFamilyAddress: text('Địa chỉ nhà gái', undefined, { maxLength: 180 }),
        brideFamilyHometown: text('Quê quán nhà gái', undefined, { maxLength: 120 }),
        groomFatherName: text('Tên ba chú rể', undefined, { maxLength: 120 }),
        groomMotherName: text('Tên mẹ chú rể', undefined, { maxLength: 120 }),
        groomFamilyAddress: text('Địa chỉ nhà trai', undefined, { maxLength: 180 }),
        groomFamilyHometown: text('Quê quán nhà trai', undefined, { maxLength: 120 }),
      },
    },
    {
      sectionKey: 'couple',
      label: 'Cô dâu và chú rể',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        brideRole: text('Vai vế cô dâu', 'brideRole'),
        groomRole: text('Vai vế chú rể', 'groomRole'),
        coupleTagline: text('Thông điệp cặp đôi'),
        coupleImage: image('Ảnh cặp đôi', 'coupleImage', 'cover'),
      },
    },
    {
      sectionKey: 'countdown',
      label: 'Đếm ngược ngày vui',
      canToggle: true,
      canReorder: true,
      fields: {
        calendarEyebrow: text('Dòng dẫn ngày vui'),
        weddingDate: text('Ngày cưới', 'weddingDate', { required: true }),
        countdownTitle: text('Tiêu đề'),
      },
    },
    {
      sectionKey: 'venue',
      label: 'Địa chỉ và bản đồ',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        ceremonyEyebrow: text('Dòng dẫn'),
        ceremonyTitle: text('Tiêu đề'),
        ceremonyMessage: multiline('Lời giới thiệu', 'ceremonyMessage', 400),
        ceremonyVenue: text('Tên nơi cử hành', 'ceremonyVenue'),
        ceremonyDate: text('Ngày cử hành', 'ceremonyDate'),
        ceremonyTime: { type: 'time', contentKey: 'ceremonyTime', label: 'Thời gian làm lễ' },
        ceremonyAddress: text('Địa chỉ nghi lễ', 'ceremonyAddress'),
        ceremonyNote: multiline('Ghi chú nghi lễ', 'ceremonyNote', 240),
        mapUrl: { type: 'url', contentKey: 'mapUrl', label: 'Đường dẫn bản đồ' },
      },
    },
    {
      sectionKey: 'calendar',
      label: 'Lịch ngày cưới',
      canToggle: true,
      canReorder: true,
      fields: { calendarEyebrow: text('Dòng dẫn ngày vui'), calendarTitle: text('Tiêu đề') },
    },
    {
      sectionKey: 'timeline',
      label: 'Lịch trình',
      canToggle: true,
      canReorder: true,
      fields: {
        timelineEyebrow: text('Dòng dẫn'),
        timelineTitle: text('Tiêu đề'),
        timelineItems: {
          type: 'items',
          contentKey: 'timelineItems',
          label: 'Các mốc thời gian',
          maxItems: 10,
          itemFields: {
            time: { type: 'time', label: 'Thời gian', required: true },
            title: text('Tên hoạt động', undefined, { required: true, maxLength: 120 }),
            detail: multiline('Mô tả', 'detail', 300),
          },
        },
      },
    },
    {
      sectionKey: 'activities',
      label: 'Hoạt động trong tiệc',
      canToggle: true,
      canReorder: true,
      fields: {
        activitiesEyebrow: text('Dòng dẫn'),
        activitiesTitle: text('Tiêu đề'),
        activities: {
          type: 'items',
          contentKey: 'activities',
          label: 'Các hoạt động',
          maxItems: 8,
          itemFields: {
            title: text('Tên hoạt động', undefined, { required: true, maxLength: 120 }),
            image: image('Ảnh hoạt động', 'image', 'activity'),
            detail: multiline('Mô tả hoạt động', 'detail', 300),
          },
        },
      },
    },
    {
      sectionKey: 'rsvp',
      label: 'Xác nhận tham dự',
      canToggle: true,
      canReorder: true,
      fields: {
        rsvpEyebrow: text('Dòng dẫn'),
        rsvpTitle: text('Tiêu đề'),
        rsvpDeadlinePrefix: text('Dòng hạn phản hồi'),
        rsvpDeadline: text('Hạn phản hồi', 'rsvpDeadline', { maxLength: 40 }),
      },
    },
    {
      sectionKey: 'gallery',
      label: 'Album ảnh',
      canToggle: true,
      canReorder: true,
      fields: {
        galleryEyebrow: text('Dòng dẫn'),
        galleryTitle: text('Tiêu đề'),
        galleryImages: {
          type: 'images',
          contentKey: 'galleryImages',
          label: 'Ảnh trong album',
          mediaRole: 'gallery',
          maxItems: 12,
        },
      },
    },
    {
      sectionKey: 'guestbook',
      label: 'Sổ lưu bút',
      canToggle: true,
      canReorder: true,
      fields: { guestbookTitle: text('Tiêu đề') },
    },
    {
      sectionKey: 'gift',
      label: 'Quà mừng cưới',
      canToggle: true,
      canReorder: true,
      fields: { giftQrMedia: image('Mã QR mừng cưới', 'giftQrMedia', 'gift-qr') },
    },
    {
      sectionKey: 'music',
      label: 'Nhạc nền',
      canToggle: true,
      canReorder: false,
      fields: {
        backgroundMusicUrl: {
          type: 'audio',
          contentKey: 'backgroundMusicUrl',
          audioNameKey: 'backgroundMusicName',
          label: 'Nhạc nền',
        },
        backgroundMusicAutoplay: {
          type: 'boolean',
          contentKey: 'backgroundMusicAutoplay',
          label: 'Tự động phát',
          default: true,
        },
      },
    },
    {
      sectionKey: 'footer',
      label: 'Lời cảm ơn',
      required: true,
      canToggle: false,
      canReorder: false,
      fields: {
        footerMessage: multiline('Lời cảm ơn', 'footerMessage', 300),
        footerImage: image('Ảnh trang trí cuối thiệp', 'footerImage', 'decor'),
      },
    },
  ],
} as const satisfies TemplateConfig
