import type { TemplateConfig } from '../../template-config'

export const woodlandLetterpressTemplateConfig = {
  templateKey: 'woodland-letterpress',
  displayName: 'Woodland Letterpress',
  templateVersion: '0.1.0',
  templateConfigVersion: '1.0',
  contentSchemaVersion: '1.0',
  rendererApiVersion: '1.0',
  status: 'draft',
  productType: 'ONLINE_INVITATION',
  type: 'invitation',
  previewPath: '/templates/invitations/woodland-letterpress/preview',
  presentation: {
    canvasMaxWidth: 450,
    outerGutterToken: 'desktop-gutter',
    mobileOnlyComposition: true,
  },
  palettes: [{ key: 'woodland', label: 'Woodland Letterpress', default: true }],
  capabilities: {
    gallery: ['3d-slide', '2d-slider', 'scroll-snap'],
    timeline: ['vertical-parallax', 'static-trail'],
    activities: ['vertical-parallax', 'static-notes'],
    smoothScroll: ['lenis-desktop', 'native-mobile'],
  },
  sections: [
    {
      sectionKey: 'cover',
      label: 'Bìa thiệp',
      required: true,
      canToggle: false,
      canReorder: false,
      layout: 'interactive-folio',
      fields: {
        brideName: { type: 'string', label: 'Tên cô dâu', required: true, maxLength: 80 },
        groomName: { type: 'string', label: 'Tên chú rể', required: true, maxLength: 80 },
        weddingDate: { type: 'date', label: 'Ngày cưới', required: true },
      },
    },
    {
      sectionKey: 'banner',
      label: 'Banner',
      required: true,
      canToggle: false,
      canReorder: false,
      layout: 'editorial-nameplate',
      fields: {
        brideName: { type: 'string', required: true, maxLength: 80 },
        groomName: { type: 'string', required: true, maxLength: 80 },
        weddingDate: { type: 'date', required: true },
      },
    },
    {
      sectionKey: 'invitation-letter',
      label: 'Lời mời và gia đình',
      required: true,
      canToggle: false,
      canReorder: false,
      layout: 'layered-paper-letter',
      fields: {
        title: { type: 'string', contentKey: 'invitationTitle', maxLength: 120 },
        message: { type: 'text', contentKey: 'invitationMessage', maxLength: 500 },
        guestGreeting: { type: 'string', contentKey: 'guestGreeting', maxLength: 160 },
        brideFatherTitle: { type: 'string', label: 'Danh xưng bố cô dâu', maxLength: 20 },
        brideFather: { type: 'string', label: 'Bố cô dâu', maxLength: 80 },
        brideMotherTitle: { type: 'string', label: 'Danh xưng mẹ cô dâu', maxLength: 20 },
        brideMother: { type: 'string', label: 'Mẹ cô dâu', maxLength: 80 },
        brideFamilyAddress: { type: 'string', label: 'Tư gia nhà gái', maxLength: 180 },
        brideRole: { type: 'string', label: 'Vai vế cô dâu', maxLength: 40 },
        groomFatherTitle: { type: 'string', label: 'Danh xưng bố chú rể', maxLength: 20 },
        groomFather: { type: 'string', label: 'Bố chú rể', maxLength: 80 },
        groomMotherTitle: { type: 'string', label: 'Danh xưng mẹ chú rể', maxLength: 20 },
        groomMother: { type: 'string', label: 'Mẹ chú rể', maxLength: 80 },
        groomFamilyAddress: { type: 'string', label: 'Tư gia nhà trai', maxLength: 180 },
        groomRole: { type: 'string', label: 'Vai vế chú rể', maxLength: 40 },
      },
    },
    {
      sectionKey: 'event-countdown',
      label: 'Event and countdown',
      required: true,
      canToggle: false,
      canReorder: false,
      layout: 'date-plaque',
      fields: {
        ceremonyDate: { type: 'date', contentKey: 'ceremonyDate', required: true },
        ceremonyTime: { type: 'time', contentKey: 'ceremonyTime', required: true },
      },
    },
    {
      sectionKey: 'calendar',
      label: 'Calendar',
      canToggle: true,
      canReorder: true,
      layout: 'woodcut-month-card',
      fields: {},
    },
    {
      sectionKey: 'venue',
      label: 'Venue',
      canToggle: true,
      canReorder: true,
      layout: 'signpost-address-card',
      fields: {
        venueName: { type: 'string', contentKey: 'venueName', required: true, maxLength: 120 },
        venueAddress: {
          type: 'string',
          contentKey: 'venueAddress',
          required: true,
          maxLength: 240,
        },
        mapUrl: { type: 'url', contentKey: 'mapUrl' },
      },
    },
    {
      sectionKey: 'timeline',
      label: 'Timeline',
      canToggle: true,
      canReorder: true,
      layout: 'vertical-parallax-trail',
      fields: {
        items: {
          type: 'items',
          contentKey: 'timelineItems',
          maxItems: 10,
          itemFields: {
            time: { type: 'time', required: true },
            title: { type: 'string', required: true, maxLength: 80 },
            detail: { type: 'text', maxLength: 240 },
          },
        },
      },
    },
    {
      sectionKey: 'activities',
      label: 'Hoạt động',
      canToggle: true,
      canReorder: true,
      layout: 'vertical-parallax-notes',
      fields: {
        items: {
          type: 'items',
          contentKey: 'activities',
          maxItems: 8,
          itemFields: {
            title: { type: 'string', required: true, maxLength: 80 },
            detail: { type: 'text', maxLength: 240 },
            image: { type: 'image', mediaRole: 'activity' },
            alt: { type: 'string', label: 'Mô tả ảnh', maxLength: 160 },
          },
        },
      },
    },
    {
      sectionKey: 'gallery',
      label: 'Gallery',
      canToggle: true,
      canReorder: true,
      layout: '3d-slide',
      fields: {
        images: { type: 'images', contentKey: 'galleryImages', mediaRole: 'gallery', maxItems: 12 },
      },
    },
    {
      sectionKey: 'rsvp',
      label: 'Xác nhận tham dự',
      canToggle: true,
      canReorder: true,
      layout: 'folded-response-card',
      fields: { message: { type: 'text', contentKey: 'rsvpMessage', maxLength: 300 } },
    },
    {
      sectionKey: 'guestbook',
      label: 'Sổ lưu bút',
      canToggle: true,
      canReorder: true,
      layout: 'hanging-note-stack',
      fields: { message: { type: 'text', contentKey: 'guestbookMessage', maxLength: 300 } },
    },
    {
      sectionKey: 'gift',
      label: 'Gift',
      canToggle: true,
      canReorder: true,
      layout: 'paper-qr-card',
      fields: {
        message: { type: 'text', contentKey: 'giftMessage', maxLength: 300 },
        qrMedia: { type: 'image', contentKey: 'giftQrMedia', mediaRole: 'gift-qr' },
      },
    },
    {
      sectionKey: 'footer',
      label: 'Lời cảm ơn',
      required: true,
      canToggle: false,
      canReorder: false,
      layout: 'closing-paper-leaf',
      fields: { message: { type: 'text', contentKey: 'footerMessage', maxLength: 300 } },
    },
  ],
} as const satisfies TemplateConfig
