import type { EnchantedForestData, EnchantedForestSectionConfig } from './content'
const forest='/assets/images/templates/enchanted-forest', hydrangea='/assets/images/templates/green-hydrangea'
export const enchantedForestFixture:EnchantedForestData={
 hero:{brideName:'Linh Chi',groomName:'Đức Anh',date:'06 · 11 · 2027',venue:'The Ancient Grove',image:`${hydrangea}/couple-hero.png`},
 announcement:{title:'A vow beneath the canopy',message:'Giữa những tầng cây cổ thụ và vệt nắng xuyên qua tán lá, chúng mình chọn trao nhau lời hẹn về một hành trình dài.'},
 couple:{bride:{name:'Linh Chi',bio:'Yêu rừng sau mưa, những trang sách cũ và sự bình yên trong những điều giản dị.',image:`${hydrangea}/bride-portrait.png`},groom:{name:'Đức Anh',bio:'Tin rằng tình yêu đẹp nhất khi hai người cùng lớn lên, như hai nhánh cây tìm thấy ánh sáng.',image:`${hydrangea}/groom-portrait.png`}},
 story:[{year:'2021',title:'Chạm nhau giữa mùa xanh',body:'Một chuyến đi ngắn qua rừng thông đã mở ra câu chuyện dài hơn mọi dự định.',image:`${forest}/forest-hero.png`},{year:'2024',title:'Những ngày vun trồng',body:'Từ căn bếp nhỏ đến những cung đường xa, chúng mình học cách cùng nhau tạo nên một mái nhà.',image:`${hydrangea}/couple-hero.png`},{year:'2027',title:'Lời hẹn dưới cổ thụ',body:'Ngày hôm nay, dưới tán rừng đã đi qua nhiều thế hệ, chúng mình bắt đầu chương mới.',image:`${forest}/forest-hero.png`}],
 events:[{date:'06.11.2027',time:'16:00',title:'Forest ceremony',venue:'The Ancient Grove',address:'Khu rừng Ánh Sáng, Đà Lạt'},{date:'06.11.2027',time:'18:30',title:'Woodland dinner',venue:'Moss Garden Hall',address:'Bên hồ Rêu Xanh, The Ancient Grove'}],
 gallery:[{src:`${hydrangea}/bride-portrait.png`,alt:'Cô dâu trong khu vườn'},{src:`${forest}/forest-hero.png`,alt:'Khu rừng tổ chức lễ cưới'},{src:`${hydrangea}/couple-hero.png`,alt:'Cặp đôi trong ngày cưới'},{src:`${hydrangea}/groom-portrait.png`,alt:'Chú rể trong khu vườn'}],
 schedule:[{time:'15:30',title:'Welcome tea',detail:'Trà thảo mộc và dạo bước trong rừng'},{time:'16:00',title:'Nghi lễ',detail:'Trao vows dưới cây cổ thụ'},{time:'18:30',title:'Tiệc tối',detail:'Bữa tối dưới ánh nến và tán cây'},{time:'20:30',title:'Forest afterglow',detail:'Âm nhạc và champagne bên hồ'}],
 dressCode:{title:'Forest formal',message:'Forest green, moss, olive, nâu gỗ và ivory sẽ hòa cùng cảnh sắc của buổi lễ.',colors:['#18372d','#355443','#71805a','#9a896b','#f3efe3']},
 faq:[{question:'Buổi lễ có ở ngoài trời?',answer:'Nghi lễ diễn ra dưới tán rừng; khu tiệc có mái kính và phương án mưa.'},{question:'Nên chọn giày thế nào?',answer:'Lối đi đã được lát phẳng, nhưng giày đế vuông hoặc đế thấp sẽ thoải mái hơn.'},{question:'Có xe đưa đón không?',answer:'Xe đón khách khởi hành từ trung tâm Đà Lạt lúc 14:45.'}],
 guestbook:[{author:'Gia đình Minh Hà',message:'Chúc hai con bền bỉ như rễ cây và luôn tìm thấy ánh sáng trong nhau.'},{author:'Nhóm Wander',message:'Mong cuộc đời phía trước của hai bạn luôn xanh, sâu và đầy điều kỳ diệu.'}],footer:{message:'Cảm ơn bạn đã bước vào khu rừng và ở lại trong ngày đặc biệt này.',signature:'Linh Chi & Đức Anh'}}
export const enchantedForestSections:EnchantedForestSectionConfig={enabled:['navigation','hero','announcement','couple','story','events','countdown','venues','gallery','schedule','dressCode','faq','rsvp','guestbook','footer'],order:['navigation','hero','announcement','couple','story','events','countdown','venues','gallery','schedule','dressCode','faq','rsvp','guestbook','footer']}
